### ISSUE TITLE
Worksheets should remember dropdown values

### ISSUE THREAD

**Issue by zsaltys** [data-dot-all/dataall#1004]
When you run a query with the worksheets module and save it should remember the last values that were set there. Especially if the query was saved. It makes sense that if you go into a saved worksheet with a saved query that you would want to be able to rerun it with a single click but you cannot do that at the moment because you have to reselect all the values on the left like environment, team etc. This is quite a frustrating UI experience. Ideally these values should be remembered even without saving. I would propose to store the last state in application state on the browser and use the worksheet_id as the bucket.. We can set some sort of TTL how long to keep this data stored on the browser.

**Comment by dlpzx** [comment]
Hi @zsaltys, yes it makes sense. So we should persist:
- selected Environment
- selected Group

Should we also store the SQL statement?

**Comment by zsaltys** [comment]
@dlpzx @noah-paige I left a comment on https://github.com/data-dot-all/dataall/issues/984 .. We could probably close this and keep 984.

**Comment by dlpzx** [comment]
Yes, I agree. I am closing this issue as the other one contains more details. Thanks!
