### ISSUE TITLE
Put a request access button directly on the dataset page

### ISSUE THREAD

**Issue by zsaltys** [data-dot-all/dataall#1008]
A lot of people don't see the lock on the catalog and click on the dataset and expect to find the request access button there. The lock is also very hard to spot and make sense of what it means.. I think we need a more intuitive button that just says "request access".

- put a request access button on the dataset ui regardless which tab ur viewing
- change the lock icon to a button with text or some other intuitive/visible alternative

**Comment by dlpzx** [comment]
Hi @zsaltys, thanks for the proposal. It is a very helpful enhancement and we will try to implement it if the bandwidth allows it. PRs are also welcomed and we will be happy to review and merge :)
