### ISSUE TITLE
Refactor access request UI flow to avoid draft shares

### ISSUE THREAD

**Issue by zsaltys** [data-dot-all/dataall#1009]
From our experience users who are using data.all for the first time find it very confusing/unintuitive that when they request access to a dataset that this creates a draft share which needs to be further filled out and then submitted. There are a few text notices for this but most folks just don't see them.

I propose that we completely get rid of access request modal and create a new page form where a user has to additionally specify what he wants to be shared with them and submitting this form actually submits the share to the dataset owner. This will ensure that it is impossible to think that a share was created and sent to another team while in fact it is still in draft mode.

I would also use this to make another improvement. From my experience a lot of new users get confused with the optional field of consumer role. They often submit an access request to their team role rather than consumer role. They then think that somehow their environment now has access and becuse they registered the roles on their environment they have access too which is obviously not the case. People don't understand what requesting access for a team means. We should make this explicit and make people choose what they want to share for - a team role or their own iam role... The change is basically making people make a conscious decision vs having an optional field which can be ignored. We want users to actively think - what should I be choosing here?

**Comment by zsaltys** [comment]
@noah-paige @dlpzx I would put a lot of priority on this one.. This one is currently causing a lot of issues where people reach out to us because they think sharing does not work when in fact the issue is because they don't understand the UI...

**Comment by dlpzx** [comment]
Hi @zsaltys thanks for the issue. There is definitely room for potential in the sharing UX. I will tag this item ans high priority and we will try to work on it as soon as possible.

**Comment by dlpzx** [comment]
Completed
