### ISSUE TITLE
Showing tables in the catalog is confusing when it matches dataset name

### ISSUE THREAD

**Issue by zsaltys** [data-dot-all/dataall#1010]
Currently the catalog shows tables and datasets. This can be very confusing if the dataset is named exactly the same as the table. What happens in our case people don't understand the difference between the two and click on the random one. If they click on the dataset then they fill out the modal and assume they got access to it but most of the time they just create a draft share which is left un-submitted. In other cases they click on the table but that will only give them access to the table and they miss to see that there's also an option to get access to an S3 bucket which is what they actually need.

This problem is partially connected to the issues described in this issue: https://github.com/data-dot-all/dataall/issues/1009

There's a few ways I could propose to fix this:

1. Remove tables from catalog UI and always request access to the dataset directly.. But i can see how this can be useful if search matches a table name but does not match a dataset name. So perhaps this is useful to have.
2. If we solve problems in [1009](https://github.com/data-dot-all/dataall/issues/1009) perhaps the access request UI can clearly show that you're creating a request for a table only and that S3 bucket access or access point access is not included in this request. Basically we need to make it very very clear that access is going to be granted to the table only and nothing else. We could also think how the listing UI can make it more clear what is being listed. Perhaps tooltips on icons. Different colours. We really need help here from UX experts.

**Comment by dlpzx** [comment]
Hi @zsaltys thanks for opening an issue. I agree with the confusion, but option 1 would be a lose for some customers that rely on table searching in the catalog. I think option 2 is an enhancement that any customer will enjoy. I would even like to have a catalog that has a hierarchical view of a dataset and its resources. Having Dataset at the top level and Buckets, tables, folders as an extension component that can be closed.
