### ISSUE TITLE
Display custom information to access requestors

### ISSUE THREAD

**Issue by zsaltys** [data-dot-all/dataall#1011]
We have a use case where a dataset owners requires that any requestors follow additional steps on internal systems. For example they ask that a JIRA ticket is filled out with a form attached that answers a bunch of questions etc. Currently there's no way to communicate from data.all that before getting access approved such steps need to be followed.

My proposal would be that each dataset has an addiitonal optional textarea to specify requirements in free form. And that these requirements are presented very clearly to the requester and they have to be CONFIRMED before a share can be submitted. That way dataset owners can make sure that requestors read required information before submitting their shares and that they know what is required of them before their shares will get approved.

**Comment by dlpzx** [comment]
Hi @zsaltys, thanks for opening an issue. This feature is partially implemented by showing the description of the Dataset in the share view. However, description is very generic and does not necessarily reflect share request requirements, so we can keep this issue open.

**Comment by zsaltys** [comment]
I think we should solve this with https://github.com/data-dot-all/dataall/issues/1065. Closing.
