### ISSUE TITLE
Add possibility to search to all team and environment dropdowns

### ISSUE THREAD

**Issue by zsaltys** [data-dot-all/dataall#1012]
I have access to a lot of environments and teams and these team and environment dropdowns are very long. There are multiple places where they are not searchable and are not sorted either. On the team invite modal the team search is sorted and searchable. I propose we use those components everywhere where we need to list teams or environments.

**Comment by dlpzx** [comment]
Hi @zsaltys, thanks for the issue. This feature is implemented in some of the select dropdowns, so we could make it the standards approach for all field selectors. We will pick it up based on bandwidth

**Comment by dlpzx** [comment]
There are multiple places where we list Environments, Teams and Consumption roles. Some can be implemented using reusable frontend components, while others are more peculiar and will be implemented as standalone frontend code snippets.

Environment list:
- [ ] RequestAccessModal.js  ([PR](https://github.com/data-dot-all/dataall/pull/1335))
- [ ] DashboardImportForm.js  
- [ ] MLStudioCreateForm.js 
- [ ] NotebookCreateForm.js 
- [ ] OmicsRunCreateForm.js 
- [ ] PipelineEnvironmentCreateForm.js 
- [ ] PipelineEnvironmentEditForm.js
- [ ] PipelineCreateForm.js 
- [ ] PipelineEditForm.js
- [ ] DatasetCreateForm.js 
- [ ] DatasetImportForm.js
- [ ] WorksheetView.js 


....

**Comment by noah-paige** [comment]
Closing this issue as it is implemented in a series of PRs:
- #1367 
- #1368 
- #1356 
- #1347 

@dlpzx - if there still remain any follow up tasks or enhancements that are "nice to have", let's open a separate issue for them
