### ISSUE TITLE
Allow to configure custom values for dataset confidentiality dropdown

### ISSUE THREAD

**Issue by zsaltys** [data-dot-all/dataall#1013]
Currently data.all comes with 3 predefined confidentiality levels. Different organizations use different levels. For example at our organization we have our own which we must use. I propose that we can define confidentiality levels inside a config file and also allow to mark which levels are strict and do not allow to view schema without data access.

**Comment by dlpzx** [comment]
Very good feature that other customers tend to customize! Thanks @zsaltys, we will see if we can prioritize it for future releases. Should Confidentiality restrict any data.all actions? I am referring to the preview being disabled for Secret datasets

**Comment by TejasRGitHub** [comment]
This is covered here - https://github.com/data-dot-all/dataall/issues/1032

**Comment by anmolsgandhi** [comment]
Completed as part of #1032
