### ISSUE TITLE
Allow to define custom values for topics on datasets

### ISSUE THREAD

**Issue by zsaltys** [data-dot-all/dataall#1014]
Topics on datasets should be configurable in a config file and there should also be a feature flag to disable this dropdown completely.

**Comment by dlpzx** [comment]
@zsaltys Thanks for the issue. The implementation will be very similar to the one for #1013 but slightly easier as no permissions are based on topics. We will implement based on bandwidth

**Comment by zsaltys** [comment]
I would not build this and focus on the metadata form feature

**Comment by dlpzx** [comment]
Closing in favor of #1065
