### ISSUE TITLE
Users Created without email id faces application issues

### ISSUE THREAD

**Issue by sandeephs1** [data-dot-all/dataall#1017]
### Describe the bug

In cognito "email id" is optional for user creations. users created without email ids are allowed to login to the Data all application but faces 2 issues as noticed - 
1st issue -
Network error occured
Network error: Failed to fetch

2nd issue -
Profile icon on the "top right corner" will not appear there by user cannot logout

### How to Reproduce

create a user in cognito without providing the "email id" and try to login with the same user id

### Expected behavior

user created with or without email id should have the same behaviour.
when email id is optional in cognito for user creation, why it is validated in application. wither make it mandatory in cognito or handle it at the application level

### Screenshots

![1_dc_userprofile_userwithoutemail](https://github.com/data-dot-all/dataall/assets/8353002/9dc40b9a-04b3-4a03-a043-7c7cf8a89730)
![2_dc_userprofile_login](https://github.com/data-dot-all/dataall/assets/8353002/14b3d065-006b-4715-934a-1e4d51c8ab57)
![3_dc_userpfofile_profilemissing](https://github.com/data-dot-all/dataall/assets/8353002/a9707f11-09ef-4b56-97ed-e19f9fe46c14)
![4_dc_userprofile_working](https://github.com/data-dot-all/dataall/assets/8353002/70248b72-cf9b-49d2-af09-6d959549a695)
![5_dc_userprofile_userWithemail](https://github.com/data-dot-all/dataall/assets/8353002/ef8f68c9-f6cb-4eb7-b00b-64d143a006dd)

### OS

Mac Sonoma 14.3

### Python version

3.9.13

### AWS data.all version

2.0.0

**Comment by dlpzx** [comment]
@sandeephs1 thanks for opening an issue, this is definitely an error that data.all users often fall into. The AWS workshop [data.all Getting Started](https://catalog.us-east-1.prod.workshops.aws/workshops/ab79ad6c-13fd-434a-ba44-9783ef2bd879/en-US/getting-started/1-cognito) already highlights that Cognito users need to verify their email. But it would be a good idea to include this error in a troubleshooting section of data.all. 

<img width="1039" alt="image" src="https://github.com/data-dot-all/dataall/assets/71252798/0df5ef61-ab77-4e0a-b7c4-a1104792ec91">

This item will be closed in favor of #1030
