### ISSUE TITLE
ML Studio - In order to use for example athena in datawrangler several permissions are missing

### ISSUE THREAD

**Issue by enr0c** [data-dot-all/dataall#1022]
### Describe the bug

When using Sagemaker Studios on glue tables that one has access to via for example athena directly, inside Sagemaker studios it throws errors. They can be clustered into two areas:

1. List operations for athena: I have identified three missing pieces: athena:ListDataCatalogs, athena:ListDatabases and athena:ListTableMetadata
2. Priviliges on S3 storage location for athenaqueries is missing

### How to Reproduce

1. Create ML Studio
2. Create a data wrangler flow
3. Add athena as connection

### Expected behavior

It should work, respecting the role the user has, as its working for example in worksheets or from a jupyter notebook

### OS

not relevant

### Python version

not relevant

### AWS data.all version

2.2.0

**Comment by ozggumus-aws** [comment]
@dlpzx this is the issue we have been discussed before. Currently we solve this problem by adding the inline policy below to the respective role manually: 

`{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "Statement1",
            "Effect": "Allow",
            "Action": [
                "s3:*"
            ],
            "Resource": [
                "arn:aws:s3:::s3bucket/athenaqueries/dataall-role-name/*",
                "arn:aws:s3:::s3bucket/athenaqueries/dataall-role-name/"
            ]
        }
    ]
}`

**Comment by enr0c** [comment]
plus the workaround for the athena: issues

`{
            "Action": [
                "athena:ListDataCatalogs"
            ],
            "Resource": [
                "*"
            ],
            "Effect": "Allow"
        },
        {
            "Action": [
                "athena:ListDatabases",
                "athena:ListTableMetadata"
            ],
            "Resource": [
                "arn:aws:athena:eu-central-1:726955877276:datacatalog/*"
            ],
            "Effect": "Allow"
        },`

**Comment by dlpzx** [comment]
Hi @enr0c we are implementing this feature as part of 2.4

One thing that I want to leave referenced is that the AWS SDK for Pandas read_sql command that we typically use has a parameter called `ctas_approach` that if set to True(default), creates a temporary table in the database. For shared databases users get READ-ONLY permissions, so this type of queries would fail. The solution is to set that parameter to False (link to [docs](https://aws-sdk-pandas.readthedocs.io/en/stable/tutorials/006%20-%20Amazon%20Athena.html)).

```
df = wr.athena.read_sql_table(
    table="table",
    database="dataall_DATABASE_shared",
    workgroup= "dataall-GROUP",
    ctas_approach=False
)
```
```
