### ISSUE TITLE
Feature flags for topics and confidentiality and custom text list for confidentiality 

### ISSUE THREAD

**Issue by TejasRGitHub** [data-dot-all/dataall#1032]
**Is your idea related to a problem? Please describe.**
When creating a dataset, the user has to mention confidentiality and topics. 

The confidentiality list / classifications types might be different from company to company. Also, those are required fields and might not be used while searching, etc. 

**Describe the solution you'd like**
In order to incorporate this requirement, add custom list to the confidentiality and create feature flags for topics and confidentiality fields so they can be disabled if required

*P.S. Don't attach files. Please, prefer add code snippets directly in the message body.*

**Comment by TejasRGitHub** [comment]
Changes required for this change  **WIP**

1. Add feature flags configs for topics and confidentiality to enable/disable on UI 
2. Add custom list for confidentiality list and keep the default in constants ( `frontend/src/modules/constants.js`) 
3. Make the UI for files `DatasetCreateForm.js` , `DatasetEditForm.js`, `DatasetImportForm.js` render conditionally the topics and confidentiality based on feature flag 
4. Change the `Catalog.js` view to display topics and confidentiality based on config 


Question to answer and clarify 

1. How does this change affect the indexing in open search ? 
2. Check if the topics and confidentiality is used on some other modules like Glossaries, Quicksight Dashboard, etc

**Comment by zsaltys** [comment]
I'd define flags as **confidentiality_dropdown** and **topics_dropdown**. It will align with other feature **glue_crawler**. Imo these are "features" and we enable/disable them. **preview_data** should be renamed to **data_preview**

I would rename **custom_confidentiality_list** to **custom_confidentiality_values** and make it a DICT like: {"Custom_Secret": {"hide_schema": true, hide_preview: "true"}}  or even simpler: {"Custom_Secret": "secret", "Custom_Secret2": "public"}

For catalog make sure to hide the topics or classification from search if those feature are disabled. Then it shouldn't affect search.

**Comment by TejasRGitHub** [comment]
Hi @zsaltys , Thanks for the suggestions. I have edited the design / code change document on this issue

**Comment by dlpzx** [comment]
We are working offline with @TejasRGitHub on the implementation of this issue

**Comment by noah-paige** [comment]
Completed as part of #1049
