### ISSUE TITLE
Data All Architecture

### ISSUE THREAD

**Issue by sandeephs1** [data-dot-all/dataall#1047]
Is Data all monolithic or microservice architecture

**Comment by noah-paige** [comment]
Data.all is a monolith in the sense that the entire application shares the same underlying infrastructure to serve API requests and persist data in Aurora DB. For example, when I create a data.all worksheet and/or I link a data.all environment - the same Lambda compute is handling the API request and communicating with the same datastore (Aurora DB).

That being said, the codebase is modularized in the sense that each “data.all module” is isolated from one another and can be plugged in (or out) of your data.all deployment at any time (via config.json file). For example, I can disable the worksheets module and I will no longer have any UI views, API handlers, etc. with respect to worksheets but the other data.all application components will continue to run fine.

Some more in-depth detail on the way data.all modules are physically structured in the codebase and loaded into the application code can be found in our [Code Walkthrough documentation](https://data-dot-all.github.io/dataall/code/).

Please let us know if you have any additional questions on the above, thanks!

**Comment by anmolsgandhi** [comment]
Hello, it appears that the question has been addressed. I'll close it for now, but feel free to reopen if you have additional questions.
