### ISSUE TITLE
Maximum policy size of 10240 bytes exceeded

### ISSUE THREAD

**Issue by sandeephs1** [data-dot-all/dataall#1048]
### Describe the bug

Linking new environments is erroring -

``` Resource handler returned message: "Maximum policy size of 10240 bytes exceeded for role dataallPivotRole (Service: Iam, Status Code: 409, 
Request ID: <>)" (RequestToken: <>, HandlerErrorCode: ServiceLimitExceeded)```

### How to Reproduce

```
*P.S. Please do not attach files as it's considered a security risk. Add code snippets directly in the message body as much as possible.*
```
Try to link new environment

### Expected behavior

Successfully should be able to link new environments

### Your project

_No response_

### Screenshots

_No response_

### OS

Mac Sonoma 14.3

### Python version

3.9.13

### AWS data.all version

2.0.0

### Additional context

_No response_

**Comment by sandeephs1** [comment]
Error is - 
Resource handler returned message: "Maximum policy size of 10240 bytes exceeded for role dataallPivotRole (Service: Iam, Status Code: 409, 
Request ID: <>)" (RequestToken: <>, HandlerErrorCode: ServiceLimitExceeded)

**Comment by dlpzx** [comment]
Hi @sandeephs, by the name `dataallPivotRole` I am guessing you are using the manually created pivot roles right? And the issue you are raising might come from creating multiple data.all Environments in the same AWS account. CDK automatically adds permissions to the environment CloudFormation custom resources SQS queues (and their KMS keys) to the pivot role. These permissions are added as inline policies, which in case of many environments might result in a policy size limit.

At the moment we support the one environment per AWS pattern, but if you confirm that this is your issue we can work on the multiple-environments in the same account approach. That way customers could have one environment per AWS account AND region.

We can prioritize https://github.com/data-dot-all/dataall/issues/936.

**Comment by sandeephs1** [comment]
Hi @dlpzx Yes we have requirement to link multiple environments with the same AWS account and a different region. also issue #936 is the request from us only. would request to prioritize the same

**Comment by dlpzx** [comment]
There was another customer with a similar issue. We have decided to include this task as an stretch goal for 2.3 (target date mid March) @sandeephs1

**Comment by sandeephs1** [comment]
Hello @dlpzx once the environment is deleted, Env policy associated to "dataallPivotRole" is not cleaned up. Whats the best way to find out the Envpolicies which are still associated but Environment is deleted so that it can be manually cleaned up and free up space.
NOTE: Have checked DB but it doesn't contain such details (like tables environment, environment_parameters)
