### ISSUE TITLE
1 revoke share and 1 approve share request running in parallel can override each other 

### ISSUE THREAD

**Issue by anushka-singh** [data-dot-all/dataall#1074]
### Describe the bug

Right now I have implemented locking mechanism only for share APPROVALS. However, during development I realized we might come across a situation where a share is revoked and approved at the same time on the same dataset. Although the chances of this happening are very rare, I thought to open a ticket to start a discussion around it. 

The solution would be to extend the locking functionality to revoke shares as well and maybe add an extra column in dataset_lock table to describe whether approval or revoke function is ongoing. 

### How to Reproduce

```
Revoke and approve couple shares on same dataset at the same time
```

### OS

Mac

### Python version

3.8

### AWS data.all version

2.2

### Additional context

https://github.com/data-dot-all/dataall/issues/941

**Comment by noah-paige** [comment]
Hi @anushka-singh - i think this is a good enhancement to the dataset lock PR you are working on

If I understand correctly, the required code changes for this enhancement would be to encapsulate the `def revoke_share(...)` logic in the same try/except block with the same calls to `acquire_lock()` and `release_lock()` as you have done for `def approve_share(...)` correct? 

Would it be possible to implement this within the same PR?

**Comment by anushka-singh** [comment]
I am testing the changes on my local env. If it succeeds then I will push it with this PR. 
If not, we can make the change shortly after. I will keep you posted.

**Comment by anushka-singh** [comment]
I have implemented this in the same PR and pushed out another commit.
