### ISSUE TITLE
CloudFormation cannot update a stack when a custom-named resource requires replacing. Rename <resource_prefix>-<git_branch>-cbprojects-sg and update the stack again.

### ISSUE THREAD

**Issue by shivalkarrahul** [data-dot-all/dataall#1080]
### Describe the bug

We tried creating 2 Pipelines in 1 Account, 1 Region and in 2 different VPCs. 1st Pipeline was successfully created, the 2nd failed with the following error.

Note: We are using different git branches for both of the pipelines.

**CloudFormation Event Log:** 

`CloudFormation cannot update a stack when a custom-named resource requires replacing. Rename dc3-stage-cbprojects-sg and update the stack again.`

<img width="1130" alt="image" src="https://github.com/data-dot-all/dataall/assets/19208841/b2de3d10-0293-47c8-9b41-aecf9f70bd9a">

**UpdatePipeline Stage Log:** 

```
Failed resources:

--
251 | dc3-stage-cicd-stack \| 11:58:22 AM \| UPDATE_FAILED        \| AWS::EC2::SecurityGroup     \| dc3-codebuild-sg (dc3codebuildsg34D8EDCF) CloudFormation cannot update a stack when a custom-named resource requires replacing. Rename dc3-stage-cbprojects-sg and update the stack again.
252 |  
253 | ❌  dc3-stage-cicd-stack failed: Error: The stack named dc3-stage-cicd-stack failed to deploy: UPDATE_ROLLBACK_COMPLETE: CloudFormation cannot update a stack when a custom-named resource requires replacing. Rename dc3-stage-cbprojects-sg and update the stack again.
254 | at FullCloudFormationDeployment.monitorDeployment (/usr/local/lib/node_modules/aws-cdk/lib/index.js:427:10615)
255 | at processTicksAndRejections (node:internal/process/task_queues:96:5)
256 | at async Object.deployStack2 [as deployStack] (/usr/local/lib/node_modules/aws-cdk/lib/index.js:430:196919)
257 | at async /usr/local/lib/node_modules/aws-cdk/lib/index.js:430:178888
```

<img width="1256" alt="image" src="https://github.com/data-dot-all/dataall/assets/19208841/99166ac5-f816-4aef-942c-ef35516506d8">

Note: 

For  Pipeline1, the event was "CREATE"
For Pipeline2, the event was "UPDATE"

Pipeline1 Screenshot

<img width="1134" alt="image" src="https://github.com/data-dot-all/dataall/assets/19208841/9c678646-2179-485e-9080-60779e464576">

Pipeline2 Screenshot

<img width="1132" alt="image" src="https://github.com/data-dot-all/dataall/assets/19208841/d0f2379b-f889-43f8-8261-beb6999f841c">

### How to Reproduce

```
Tooling Account: Account1
Deployment Account: Account2

Pipeline 1 in Account1: (Same Account)
tooling_region: eu-west-1 (Same Region)
tooling_vpc_id: vpc_1 (Different VPC)


Pipeline 2 in Account1: (Same Account)
tooling_region: eu-west-1 (Same Region)
tooling_vpc_id: vpc_2 (Different VPC)

Pipeline 1 : cdk deploy dc2-qa-cicd-stack
Pipeline 2 : cdk deploy dc3-stage-cicd-stack

```

### Expected behavior

If creating multiple pipelines in 1 Account, 1 Region, different VPCs is supported, then the pipeline should complete successfully.

### Your project

https://github.com/data-dot-all/dataall/tree/v2.0.0

### OS

NA

### Python version

NA

### AWS data.all version

v2.0.0

**Comment by dlpzx** [comment]
Hi @shivalkarrahul that is a very strange error, from the data you provided I am guessing that:
Pipeline 1: resource_prefix = `dc2`, git_branch = `qa`
Pipeline 2: resource_prefix = `dc23`, git_branch = `stage`

The resource that is failing is a CodeBuild security group, with the name `security_group_name=f'{self.resource_prefix}-{self.git_branch}-cbprojects-sg',` Because the names of the security groups are completely different I do not think the root cause of the issue is related to having 2 pipelines.

This error is not unusual and there is this [AWS re:Post answer](https://repost.aws/knowledge-center/cloudformation-custom-name) that explains why it happens:

```
This error typically occurs when a stack update tries to replace resources that have properties with custom names. AWS CloudFormation doesn't replace a resource that has a custom name unless that custom name is changed to a different name. To prevent a stack failure and avoid the error message, change any resources with custom names to use different names before you update a stack.

The resolution for this error assumes the following:

    You're updating an existing stack and not creating a new stack.
    You're changing the names of existing custom-named resources and not creating new custom-named resources.

```

Did you created the pipeline with different values for git_branch and resource_prefix and then updated those values to `dc3` and `stage` that could be a cause.

**Comment by shivalkarrahul** [comment]
Hi @dlpzx,
Thank you for your response.

A few things:

- 1. Pipeline 2: resource_prefix = dc23, git_branch = stage --> The prefix is not dc23 in our case, it is dc3(was dc23  a typo by you?)
- 2. Because the names of the security groups are completely different I do not think the root cause of the issue is related to having 2 pipelines. --> You meant, dc2-qa-* and dc3-stage-*, in case of both the pipelines, right? Yes, they are different.
- 3. You're updating an existing stack and not creating a new stack. --> We are not updating the stack, we are creating a new one using "cdk deploy dc3-stage-cicd-stack" command.
<img width="1135" alt="image" src="https://github.com/data-dot-all/dataall/assets/19208841/0109fd9c-dc7e-4b23-9b68-5b135f95309f">
- 4. You're changing the names of existing custom-named resources and not creating new custom-named resources. --> We are not doing that, we checked that before the CloudFormation runs, there was no such resource in the account.
- 5. Did you created the pipeline with different values for git_branch and resource_prefix and then updated those values to dc3 and stage that could be a cause. --> No, we used the "cdk deploy dc3-stage-cicd-stack" command to create the pipeline, and it took care of everything.

Please let us know your thoughts.

We will still try to create a new pipeline once again from our side. 
 
 Thank you.

**Comment by shivalkarrahul** [comment]
Retried with a different prefix(dc4), and it worked. Hence, closing the issue.
