### ISSUE TITLE
Lambda does not have permission to access the ECR image

### ISSUE THREAD

**Issue by shivalkarrahul** [data-dot-all/dataall#1086]
### Describe the bug

Hello Team,

We tried deploying 2 Data.all application instances in the same AWS Account but in different regions.
The first deployment(application instance) was successful. However, the second deployment(application instance) failed.

### How to Reproduce

```
Tooling Account A
Region= eu-west-1
Pipeline 1 in VPC1 --> Working
Pipeline 2 in VPC2 --> Failing



Deployment Account B:
Application Instance 1:  Region = eu-west-1 --> Working
Application Instance 2:  Region = us-east-1 --> Unsuccessful 


Commands:
Application Instance 1: cdk deploy dc2-qa-cicd-stack
Application Instance 2:  cdk deploy dc4-stage-cicd-stack

```

### Expected behavior

If supported, 2 Data.all deployments should work in 1 AWS Account and 2 different regions.

### Your project

https://github.com/data-dot-all/dataall/tree/v2.0.0

### Screenshots

**2 Pipelines in Tooling Account A**
<img width="1084" alt="image" src="https://github.com/data-dot-all/dataall/assets/19208841/745b3840-fdf0-45a8-8f63-b8e6f441aed3">

**Error in Pipeline2 stage=dc4-ops4-backend-stage in Tooling Account A**
`Embedded stack arn:aws:cloudformation:us-east-1:801758280565:stack/dc4-ops4-backend-stage-backend-stack-LambdasNestedStackLambdasNestedStackResource871D3-RMOU0YZWFI0V/266366f0-da0e-11ee-99cf-125f044e0c37 was not successfully created: The following resource(s) failed to create: [ElasticSearchProxyHandlerDBDE7574, LambdaGraphQL1131F2C3, AWSWorkerAA1523CA].`
<img width="828" alt="image" src="https://github.com/data-dot-all/dataall/assets/19208841/254e1e27-c846-4e8f-8d67-120eb6e471ec">

**Error in Cloudformation in Deployment Account B**
`
2024-03-04 15:32:38 UTC+0530 | LambdasNestedStackLambdasNestedStackResource871D36BA | CREATE_FAILED | Embedded stack arn:aws:cloudformation:us-east-1:801758280565:stack/dc4-ops4-backend-stage-backend-stack-LambdasNestedStackLambdasNestedStackResource871D3-RMOU0YZWFI0V/266366f0-da0e-11ee-99cf-125f044e0c37 was not successfully created: The following resource(s) failed to create: [ElasticSearchProxyHandlerDBDE7574, LambdaGraphQL1131F2C3, AWSWorkerAA1523CA].
-- | -- | -- | --

`
<img width="1235" alt="image" src="https://github.com/data-dot-all/dataall/assets/19208841/6c950c0a-fd76-44c8-98e2-7ecc1084e7d1">

**Error in Nested Cloudformation in Deployment Account B**
<img width="1170" alt="image" src="https://github.com/data-dot-all/dataall/assets/19208841/01031d62-d712-4a9b-82ae-746c2cf76c4c">

### OS

NA

### Python version

NA

### AWS data.all version

v2.0.0

**Comment by dlpzx** [comment]
Hi @shivalkarrahul, thanks for documenting the issue. Your CloudFormation stack is failing because you are deploying from one region in tooling `eu-west-1` to a different region for the infra `us-east-1`. We should make the docs more clear about this point because it is not possible to deploy the docker images stored in ECR in the tooling account/region for Lambda functions in a different region (infra account region). The solution is to have the CICD pipeline in the same region as the infrastructure.

We will make it more explicit in the docs, because it is certainly misleading. Sorry for the inconvenience

**Comment by shivalkarrahul** [comment]
Hi @dlpzx ,
Thank you for your quick response.
Any plans to implement this?

**Comment by shivalkarrahul** [comment]
Hi @dlpzx ,
We could not deploy multiple CICD pipelines, however, this(cross region deployment) is not a blocker for us for now.

**Comment by dlpzx** [comment]
We updated the documentation in #1175. @shivalkarrahul can we close this item? Or do you require cross-region deployments?

**Comment by shivalkarrahul** [comment]
Hello @dlpzx ,

You may feel free to close this now. 
We currently don't have a requirement for the cross-region deployments.
Thank you.
