### ISSUE TITLE
Extend locking mechanism to different resources

### ISSUE THREAD

**Issue by anushka-singh** [data-dot-all/dataall#1093]
**Is your idea related to a problem? Please describe.**
We implemented locking for dataset level. However, we are now facing issues when 2 or more shares are getting approved for the same requestor at the same time. This gives rise to a race condition where the IAM policy of requestor is modified at the same time. 
We observed an error like: 
```
Failed to update policy SHARE_POLICY_ARN : An error occurred (NoSuchEntity) when calling the DeletePolicyVersion operation: Policy SHARE_POLICY_ARN version v3 does not exist or is not attachable.
```

Example:
- UserA in GroupA requests shares to bucket in Dataset B_1 and folder in Dataset B_2
- GroupB (who owns both datasets) approves the share at the same time
- Both shares will be processed at the same time and update the IAM share policy of UserA to give S3 and KMS permissions to the resources (here causes the error)

**Describe the solution you'd like**
Think about a way to extend locking mechanism beyond just dataset locking to different resource types. What if we need to lock resource X during activity Y (i.e. lock datasets from other actions when updating, or similar)

*P.S. Don't attach files. Please, prefer add code snippets directly in the message body.*

**Comment by dlpzx** [comment]
@anushka-singh thanks for opening an issue. This feature came up during validation of 2.3. Do you think you have capacity to take on the extension? In any case, we have added it to our 2.5 project and try to pick it up as soon as possible.

**Comment by anushka-singh** [comment]
@dlpzx I will be working on expiration of shares feature next. But if I have bandwidth for 2.5 then can pick this up shortly after.

**Comment by noah-paige** [comment]
Thoughts on the design for this issue below...

**Changes to DB Schema**
- Rename `dataset_lock` to `resource_lock`
- Rename column `datasetUri` to `resourceUri`
- Add column `acquiredByResourceType` to represent a string/enum value for what resource it is acquired by (i.e. `share`, etc.)
  - This will be additional information alongside the `acquiredBy` Column to store the `shareUri`
  - Do we think this would be useful in long-run (i.e. think if we extend locking to not only be a part of the sharing mechanism) ?

**Changes to Share Logic**
- Check if either datasetUri is locked **_OR_** Requester Principal is locked
  - OPEN ENDED Q: The primary key for Env Group is composite key of groupUri and environmentUri
    - This issue is that GroupA can request access from many dif Envs (need to check lock for groupUri-envUri pair!)
    - Option A - in `resourceUri` column store concatenated Uri Pair (`'groupUri-envUri'`)
    - Option B - in `resourceUri` column store `environmentIAMRoleArn` (in this case maybe `resourceUri` is the wrong name for the column)
    - Option C - introduce `resourceEnvUri` column and make it a composite key along with `resourceUri` ++ backfilling


Please take a look @anushka-singh @dlpzx - I will get on implementing the above shortly but there are some open questions I would appreciate input on

**Comment by anushka-singh** [comment]
Hey Noah,
Thanks for picking this up and coming up with a design on this. 
I am OOO tomorrow, but I will get back to you on this by Thursday.

**Comment by anushka-singh** [comment]
> Thoughts on the design for this issue below...
> 
> **Changes to DB Schema**
> 
> * Rename `dataset_lock` to `resource_lock`
> * Rename column `datasetUri` to `resourceUri`
> * Add column `acquiredByResourceType` to represent a string/enum value for what resource it is acquired by (i.e. `share`, etc.)
>   
>   * This will be additional information alongside the `acquiredBy` Column to store the `shareUri`
>   * Do we think this would be useful in long-run (i.e. think if we extend locking to not only be a part of the sharing mechanism) ?

- Agree to the DB schema changes. 
- Yes I think we should extend locking and not just keep it restricted to sharing. We have discussed in the past that we should introduce resource level locking for datasets, environments and organizations etc when they are undergoing updates. It can be used in tandem with the maintenance window work to ensure processes are paused when updates on these resources start and are picked up again when maintenance window is complete. 


> **Changes to Share Logic**
> 
> * Check if either datasetUri is locked **_OR_** Requester Principal is locked
>   
>   * OPEN ENDED Q: The primary key for Env Group is composite key of groupUri and environmentUri
>     
>     * This issue is that GroupA can request access from many dif Envs (need to check lock for groupUri-envUri pair!)
>     * Option A - in `resourceUri` column store concatenated Uri Pair (`'groupUri-envUri'`)
>     * Option B - in `resourceUri` column store `environmentIAMRoleArn` (in this case maybe `resourceUri` is the wrong name for the column)
>     * Option C - introduce `resourceEnvUri` column and make it a composite key along with `resourceUri` ++ backfilling

- For checking  env group, I like option A the best. It is easy to implement and does not need a new column introduced either. 

> Please take a look @anushka-singh @dlpzx - I will get on implementing the above shortly but there are some open questions I would appreciate input on

**Comment by noah-paige** [comment]
We have implemented this extension of locking mechanism to be generic for any resource rather than dataset specific in PR #1338 

We went with Option A above as a rule of thumb to concatenate Uri Pair for records that have composite primary keys
- For example for EnvGroups (table = `enviornment_group_permission`) the composite key is `groupUri` and `environmentUri` so the primary key identifier in Resource Lock table is ``'groupUri-envUri'``

We also changed the model such that `acquire_lock` will create records in the table and `release_lock` will delete records - this way there is no requirement to add `create_lock` and `delete_lock` logic whenever we create/delete a new resource and any resource can leverage the locking class functions without additional custom logic

I will go ahead and close this issue - thanks for all the design considerations and help in above thread!

cc: @anushka-singh
