### ISSUE TITLE
Handle Entire Folder Revoke + Clean Up Before Share Process Succeeds

### ISSUE THREAD

**Issue by noah-paige** [data-dot-all/dataall#1101]
### Describe the bug

When revoking a folder share item 
- The share item updates to `Revoke_Succeeded` once the access point policy is updated to remove the folder prefix for the principal IAM role

But if there are no additional folder shares for the same principal we perform a number of other steps, including:
- Delete Access Point
- Remove access point permissions from princinpal IAM Role share policy 
- Updates to the KMS policy permissions to remove principal IAM Role

The above actions all happen after the folder item is already updated to `Revoke_Succeeded` but theoretically the revoke process could fail in those steps and then there are pending resources remaining in the account that should have been cleaned up - and no way for data.all to notify the user or try again to clean up currently

### How to Reproduce

```
*P.S. Please do not attach files as it's considered a security risk. Add code snippets directly in the message body as much as possible.*
```

### Expected behavior

data.all updated to a Revoke_Succeeded status only when it is done cleaning up all resources related to the share item and/or notifies the user when it fails to clean up some particular resource

### OS

N/A

### Python version

N/A

### AWS data.all version

v2.2.0

**Comment by dlpzx** [comment]
Merged!
