### ISSUE TITLE
Enhancements related to UI for the share verify and re-apply feature

### ISSUE THREAD

**Issue by anushka-singh** [data-dot-all/dataall#1107]
**Is your idea related to a problem? Please describe.**
In my testing for feature: https://github.com/data-dot-all/dataall/pull/1062/files I found some enhancements that can be made to the frontend. We can do this as a part of 2.4 if we so choose. They are really minor changes but would lead to overall better user experience. 
1. The font/text size of the hover over the health status icon is different from everything else on the page. Check `Healthy` in the screenshot below
<img width="1459" alt="Screenshot 2024-03-14 at 7 31 15 PM" src="https://github.com/data-dot-all/dataall/assets/26413731/1b764c86-dbc5-4d37-b49e-24aabef0d10c">

2. Bug: After clicking on verify status button, the page does not auto-refresh with updated status and timestamp. I need to hit refresh on the page every-time to get an updated status. 

3. When revoke succeeded, health status states `Undefined` instead of `None` or something a little more meaningful. Also, the `...` is a little misleading because as a user, I keep waiting for it to change. We can also remove status altogether and replace with a dash `-`. That might be more meaningful. 
<img width="541" alt="undefined-verify" src="https://github.com/data-dot-all/dataall/assets/26413731/8c732616-fd48-430c-b403-4c0cd4bd5651">

4. While a share item is in 'PendingReApply'. I still have the option to revoke the item. I think we should block off that option when share is being fixed, to avoid inconsistency. 

5. When I hit verify on the overall dataset, there is a pop-up saying verify has started. After that, as a user I would be confused as there is no UI update on this page. 
Only if I open the share request, do I see that verification is in progress. There is no status update here at all. I am not notified that verification is complete. We could have a UI pop-up redirecting users to the individual share request pages to track the status of the health check and to re-apply shares if anything is broken. We could also have a button here to re-apply shares to all failed verification checks.

*P.S. Don't attach files. Please, prefer add code snippets directly in the message body.*

**Comment by dlpzx** [comment]
Hi @anushka-singh thank you for opening an issue. It is perfectly explained and some of the things are quick wins. We will add this item to 2.5 (UX improvements) project and address as many items as possible

**Comment by dlpzx** [comment]
Completed in #1346
