### ISSUE TITLE
Notifications regarding share requests should be clickable and link to the relevant request

### ISSUE THREAD

**Issue by Yehudavidor** [data-dot-all/dataall#1115]
**Is your idea related to a problem? Please describe.**
I'm frustrated whenever I get a notification regarding a share request, but there's no way to get from the notification itself into the share request.

**Describe the solution you'd like**
I'd like the notification text itself to be clickable, and direc tthe user to the relevant share request
*P.S. Don't attach files. Please, prefer add code snippets directly in the message body.*

**Comment by dlpzx** [comment]
Thanks @Yehudavidor for opening an issue. We are currently adding UX-focused issues to 2.5 and this issue is a good candidate. We will work on it.
