### ISSUE TITLE
Merge v2.3.0 with v.2.0.0

### ISSUE THREAD

**Issue by shivalkarrahul** [data-dot-all/dataall#1116]
Hello Team,

We are currently using v.2.0.0 and plan to merge v2.3.0 with it.
We tried to merge it locally and got conflicts which was obvious. [ We used the v.2.3.0 tag, created a temp branch out of the tag hash and merged it in our new branch.]

We have a few questions as follows, but not limited to:
1. What would be the best way to resolve these conflicts?
2. Earlier there was "if self.source == 'github'" block of code in deploy/stacks/pipeline.py, but in the latest changes we don't see that. Does that mean there is no need to check if the souce is github or github is not supported? 
3. Earlier there was "permissions_boundary" in "deploy/app.py" and now it is not there? Does it mean it is no more supported or handled in any other way?

These are just reference questions. There could be a lot of such scenarios. 

The main questions are: 
1. What all challenges we may face during the upgrade activity and how should we proceed?
2. What is the best way to upgrade from v.2.0.0 to v2.3.0?

Thank you.

**Comment by dlpzx** [comment]
Hello @shivalkarrahul thanks for opening an issue. I think we can divide the problems into 2: firstly the resolution of conflicts (1 in your list) and secondly changes in features (2 and 3).

I tried reproducing the conflicts issue (created a branch with 2.0.0 out of the v2.0.0 tag and another branch for the tag 2.3.0, then I merged 2.3 into 2.0). Unfortunately I was not able to reproduce the conflicting errors :S Conflicts might arise from custom commits, which I think is your case.


For the second issue, changes to existing features. The first thing to do is to review the release notes. For the second item on the source==github, in [release 2.2.0](https://github.com/data-dot-all/dataall/releases/tag/v2.2.0) the support has been improved in this [PR](https://github.com/data-dot-all/dataall/pull/834).

As for the permissions_boundary issue, I am not sure I understand what you are referring to. I tried searching for permissions, boundaries in deploy/app.py but I could not easily find any reference (in the code of v2.0.0). Can you give me more hints? 

In a more generic note, I have been reviewing the release notes for 2.1.0, 2.2.0 and 2.3.0. As you can verify, there are some warnings for 2.1 and 2.3. 2.2 should be a smooth upgrade. It is worth having a look at the list of features of each release before upgrading, so there are no surprises. 

I will keep this issue open in case you still face issues

**Comment by shivalkarrahul** [comment]
Hi @dlpzx ,

Thanx for your response.

permissions_boundary -> Please ignore this.
