### ISSUE TITLE
Cognito User Group data

### ISSUE THREAD

**Issue by sandeephs1** [data-dot-all/dataall#1127]
User and groups data created in Cognito, does Data All stores it in RDS or any other storage?

**Comment by dlpzx** [comment]
Hi @sandeephs1, thanks for the question.

Users and groups created in Cognito are only stored in Cognito. Data.all creates permissions for each group once at least one user belonging to that group has logged into data.all. In the table `tenant_policy` we store these "active" groups in the `principalId` column: dataall/core/permissions/db/permission_models.py:33. Users are not stored in RDS.

Let us know if you need more clarifications. Also, why are you looking into this information? Are you going to use it or do you need to ensure that those details are not collected?

**Comment by sandeephs1** [comment]
Thanks @dlpzx
we are planning for external tool integration with Data all, which would require us to manage users and groups between Data all and External tool. So wanted to confirm if user group data is stored in any other object/source

**Comment by dlpzx** [comment]
Thanks for the context @sandeephs1, in your scenario we have seen that other users of data.all manage users and groups directly in the external tool . Do you have any other pending questions?
