### ISSUE TITLE
share revoke should not fail when a role is deleted

### ISSUE THREAD

**Issue by zsaltys** [data-dot-all/dataall#1141]
We've ran into multiple situations where our users delete a role which is actively used in data.all. We can detect this (with custom scripts) and data.all will let you revoke the S3 share via UI but it will fail trying to revoke a LakeFormation share with an error like:

`Failed to get role ROLE_NAME due to: An error occurred (NoSuchEntity) when calling the GetRole operation: The role with name ROLE_NAME cannot be found.`

This can only be fixed by manually updating the share to FAILED in RDS and then the share can be deleted via UI. This is very inconvenient because only data.all engineering team can fix such issues rather than making it a responsibility of the share owner.

I suspect that this issue also affects the "share validator" released in 2.3 and that it fails to fix a share when a role is deleted. I propose the following enhancement for this problem:

When attempting to revoke a share detect that a role has been deleted/missing and simply put the share into FAILED mode so that the share can be deleted via UI. This should also happen when share fixer is trying to fix the share either via manual request or when it runs in the background.

This fix is related to this issue https://github.com/data-dot-all/dataall/issues/1029. The above error was observed on 2.2 release.

**Comment by anushka-singh** [comment]
#### Confirming re-apply shares wont work if role was deleted for a successful share:

I had a successful share, then I deleted the consumption role. 
Verify shares, marked share as unhealthy with following errors:
![Screenshot 2024-04-03 at 9 37 09 AM](https://github.com/data-dot-all/dataall/assets/26413731/f4e3f9f7-53f2-4b2e-8a5f-17507f65c5c0)
When I hit re-apply shares, it does work and fails with error:
<img width="1455" alt="Screenshot 2024-04-03 at 9 41 17 AM" src="https://github.com/data-dot-all/dataall/assets/26413731/81b8e230-b7ae-4790-84ca-eaccc0a20278">

**Comment by SofiaSazonova** [comment]
I think, the most logical way to handle this is:
1. Check the existence of the role during the healthcheck. Make it the first important statement in the result.
2. If during the healthcheck the role is missing, dataall must revoke all resource permissions and delete dataall managed policies, the share must become 'failed'
3. Revoke/Reapply share must lead to status 'Share failed', if there is no consumption role. Additionaly dataall must revoke all resource permissions and delete dataall managed policies
@zsaltys @dlpzx @anushka-singh what do you think?

**Comment by dlpzx** [comment]
Completed in #1161
