### ISSUE TITLE
Email notification do not contain share link 

### ISSUE THREAD

**Issue by TejasRGitHub** [data-dot-all/dataall#1142]
### Describe the bug

When data.all is deployed with email notifications enabled for share actions. the email notifications are sent but do not contain share link as per work done here - https://github.com/data-dot-all/dataall/pull/1082

### How to Reproduce

1.Enable email notifications in data.all by switching/configuring as described here - https://data-dot-all.github.io/dataall/deploy-aws/
2. Create a share request 
3. Submit a share request
4. Email notifications won't contains the share link

### Expected behavior

Email notifications should contain share link 

### OS

Mac

### Python version

3.9

### AWS data.all version

2.3

**Comment by dlpzx** [comment]
Hi @TejasRGitHub is this issue fully fixed in #1143?

**Comment by TejasRGitHub** [comment]
Hi @dlpzx , Yes this is fully fixes in #1143
