### ISSUE TITLE
Dataall Table Improvements = Fixes

### ISSUE THREAD

**Issue by noah-paige** [data-dot-all/dataall#1171]
### Describe the bug

I think there are a couple of TABLE permissions items to handle on a separate PR:
    1. clean-up permissions to env.admin
    2. implement delete permissions on deletes of tables
    3. decorate get_tables with GET_TABLE permissions

(1) Previous Env Admins used to get permissions to new dataset tables - we remove that in PR #1163 but did not delete permission from older tables (i.e. envAdmins should not have DATASET_TABLE_READ permissions (unless they are the steward or datasetAdmin)

(2) Implement delete of dataset table permission when we delete dataset table (either delete via UI but also how do handle sync of tables when tables no longer exist on glue)

(3) decorate get_tables with GET_TABLE permissions

### How to Reproduce

```
*P.S. Please do not attach files as it's considered a security risk. Add code snippets directly in the message body as much as possible.*
```

### OS

N/A

### Python version

N/A

### AWS data.all version

2.3

**Comment by dlpzx** [comment]
Thanks for the issue!

**Comment by anmolsgandhi** [comment]
@noah-paige can this issue be closed?

**Comment by noah-paige** [comment]
Closing this issue as completed in #1237
