### ISSUE TITLE
Enable encryption for ECR in the ecr stack

### ISSUE THREAD

**Issue by mourya-33** [data-dot-all/dataall#1200]
### Describe the bug

Currently, the ECR repository created as part of the ECR stack is not encrypted. This is flagged by checkov as the following failure.

CheckID		: CKV_AWS_136 
CheckName	: Ensure that ECR repositories are encrypted using KMS
File		: /cdk.out/assembly-dataall-pr-cicd-stack-dataall-ecr-stage/dataallprcicdstackdataallecrstageprecrstack3C1CC298.template.json:3-101
Resource	: AWS::ECR::Repository.ECRRepositoryF3A3832E

### How to Reproduce

run checkov scan on the ecr stack template to see the encryption check failures

### Expected behavior

ECR repository should be encrypted and the checkov scan check should succeed.

### OS

Mac

### Python version

3.10

### AWS data.all version

2.3

**Comment by dlpzx** [comment]
This is a great addition, thanks for opening the issue @mourya-33

**Comment by mourya-33** [comment]
This issue is fixed and merged
