### ISSUE TITLE
Enable encryption for environment variables in lambdas

### ISSUE THREAD

**Issue by mourya-33** [data-dot-all/dataall#1201]
### Describe the bug

The lambda environment variables are not encrypted. This is flagged by checkov as failures

CheckID		: CKV_AWS_173
CheckName	: Check encryption settings for Lambda environmental variable
File		: /cdk.out/assembly-dataall-pr-cicd-stack-dataall-staging-backend-stage/dataallprcicdstackdataallstagingbackendstagebackendstackLambdas82440D4F.nested.template.json:509-591
Resource	: AWS::Lambda::Function.ElasticSearchProxyHandlerDBDE7574

CheckID		: CKV_AWS_173
CheckName	: Check encryption settings for Lambda environmental variable
File		: /cdk.out/assembly-dataall-pr-cicd-stack-dataall-staging-backend-stage/dataallprcicdstackdataallstagingbackendstagebackendstackLambdas82440D4F.nested.template.json:1102-1187
Resource	: AWS::Lambda::Function.LambdaGraphQL1131F2C3

CheckID		: CKV_AWS_173
CheckName	: Check encryption settings for Lambda environmental variable
File		: /cdk.out/assembly-dataall-pr-cicd-stack-dataall-staging-backend-stage/dataallprcicdstackdataallstagingbackendstagebackendstackLambdas82440D4F.nested.template.json:1765-1851
Resource	: AWS::Lambda::Function.AWSWorkerAA1523CA

CheckID		: CKV_AWS_173
CheckName	: Check encryption settings for Lambda environmental variable
File		: /cdk.out/assembly-dataall-pr-cicd-stack-dataall-staging-backend-stage/dataallprcicdstackdataallstagingbackendstagebackendstackLambdas82440D4F.nested.template.json:2004-2069
Resource	: AWS::Lambda::Function.CustomAuthorizerFunctionstagingE5F02094

CheckID		: CKV_AWS_173
CheckName	: Check encryption settings for Lambda environmental variable
File		: /cdk.out/assembly-dataall-pr-cicd-stack-dataall-staging-backend-stage/dataallprcicdstackdataallstagingbackendstagebackendstackS3ResourcesDFBD799A.nested.template.json:655-698
Resource	: AWS::Lambda::Function.CustomCDKBucketDeployment8693BB64968944B69AAFB0CC9EB8756C81C01536

### How to Reproduce

run checkov scan on the lambda stack templates to see the failures.

### Expected behavior

Once the env variables are encrypted, the checkov scans should succeed.

### OS

Mac

### Python version

3.10

### AWS data.all version

2.3

**Comment by dlpzx** [comment]
Similar to the ECR PR, this is a great addition that benefits all users. Thanks for opening an issue @mourya-33

**Comment by dlpzx** [comment]
Completed in #1225
