### ISSUE TITLE
cdkExecPolicy doesn't reference EnvironmentResourcePrefix in the cloudformation permissions section

### ISSUE THREAD

**Issue by TejasRGitHub** [data-dot-all/dataall#1202]
### Describe the bug

Please refer to the image. This is the section of cdkExecPolicy.yaml. Here the environmentPrefix variable doesn't contain a '$' before the EnvironmentResourcePrefix due to which it literally contains {EnvironmentResourcePrefix} string in the cdkExecPolicy

<img width="1186" alt="image" src="https://github.com/data-dot-all/dataall/assets/71188245/7ff7c9a6-393a-4974-91a4-3b5524132631">

### How to Reproduce

1. Install the cdkExecPolicy on data.all via CF
2. Inspect policy to check if the EnvironmentResourcePrefix is present in the section where it gives permission on cloudformation resources

### Expected behavior

Should contain the actual EnvironmentResourcePrefix value 

### OS

Mac

### Python version

3.9

### AWS data.all version

2.4

**Comment by dlpzx** [comment]
Solved in #1204
