### ISSUE TITLE
Allow DA admins to view share logs

### ISSUE THREAD

**Issue by zsaltys** [data-dot-all/dataall#1215]
There can be many reasons why shares fail and we've had to many times log into infra account to view share manager logs. It would be really nice if DAAdministrators could have a button next to each share item which opens a modal with the CloudWatch logs when this share last ran. We have a similar modal for dataset and environment stacks.

**Comment by SofiaSazonova** [comment]
To implement this we need
1. Apply the same solution we have for the Stack Logs
2. The tricky part: identify the log for the share task. Right now there is no way to identify the share by log-name. It's to be researched.
