### ISSUE TITLE
Integration tests executed on a real deployment as part of the CICD  - Environments

### ISSUE THREAD

**Issue by dlpzx** [data-dot-all/dataall#1230]
Description in #1220.

This issue is to track the progress for the `Environments` module. 
It has its complications because we need to work with real AWS accounts that need to be bootstrapped and trusting the real deployment account. 

Design will follow

**Comment by petrkalos** [comment]
In #1334 some basic tests that create/delete/modify an environment were added but more should be added to  cover the most commonly used functionality around environments

**Comment by dlpzx** [comment]
Completed!
