### ISSUE TITLE
Update documentation after v2.5 release for dataset related changes

### ISSUE THREAD

**Issue by TejasRGitHub** [data-dot-all/dataall#1268]
**Is your idea related to a problem? Please describe.**
Documentation provided here - https://data-dot-all.github.io/dataall/deploy-aws/ does not contain the new config.json related changes like the change from datasets to s3_buckets and datasharing module. 

This could cause deployment issue when upgrading from v2.3, v2.4 to v2.5 as the configs will be missing 

If any infrastructure creation / deletion is tied to this config, then it might impact data.all upgrade and currently present data.all dataset functionality 

**Describe the solution you'd like**
Update the documentation to reflect those changes

*P.S. Don't attach files. Please, prefer add code snippets directly in the message body.*

**Comment by noah-paige** [comment]
Thanks for the call out - addressed in #1269, closing this issue
