### ISSUE TITLE
Automated Share Correction with Re-Apply Share ECS Task

### ISSUE THREAD

**Issue by anushka-singh** [data-dot-all/dataall#1285]
**Is your idea related to a problem? Please describe.**
We have Share Verifier ECS task scheduled to run weekly. Occasionally, this leads to shares being marked as unhealthy. Thankfully, the 'Re-Apply Share' button proves to be a valuable resource, resolving most of these issues upon activation.

**Describe the solution you'd like**
There is a need to introduce a new ECS task specifically for re-applying shares. This task can execute after the Share Verifier task, allowing for automatic correction of shares without the need for manual intervention.

*P.S. Don't attach files. Please, prefer add code snippets directly in the message body.*

**Comment by dlpzx** [comment]
This is a great idea that does not require a lot of additional efforts on top of what we have already implemented :) Are you planning to take it?

**Comment by noah-paige** [comment]
Hello - we have opened a PR that adds a step to the share verifier task that will also start the reapplier task to try and re-apply/fix for any unhealthy share items after verification of all share items is complete

Currently the implementation is default behavior when the verifier task is triggered - please let me know thoughts after taking a look at the PR

@anushka-singh @zsaltys

**Comment by anushka-singh** [comment]
Added a comment on the PR
