### ISSUE TITLE
Unable to load consumption roles on request modal page for large number of consumption roles

### ISSUE THREAD

**Issue by TejasRGitHub** [data-dot-all/dataall#1288]
### Describe the bug

When requesting a share from the catalog page, after selecting a team for an environment the consumption roles do not populate. The UI shows "Network Error" and checking the browser dev tools in the network tab, the call `listEnvironmentConsumptionRoles` is returning Gateway timeout 504. 

This is probably because the graphQL resolver used for listEnvironmentConsumptionRoles fetches information about if the consumption roles are managed or not, etc. This checking incurs doing boto3 calls by assuming pivot role in all associated aws environment accounts. 

### How to Reproduce

```
*P.S. Please do not attach files as it's considered a security risk. Add code snippets directly in the message body as much as possible.*
```
1. Create 25 - 30  consumption roles 
2. Add these consumption roles under **one team** as owner. 
3. Goto Catalog and request access to a dataset 
4. During requesting access to the dataset, select this team 
5. The consumption roles drop down doesn't load

### Expected behavior

The consumption role dropdown should load with all consumption roles associated with that team

### OS

Mac

### Python version

3.9

### AWS data.all version

2.5

**Comment by SofiaSazonova** [comment]
Thanks for the bugreport @TejasRGitHub !
I had a look into resolvers and can admit, that it may cause issue.

**Comment by SofiaSazonova** [comment]
@TejasRGitHub  please test `[this PR](https://github.com/data-dot-all/dataall/pull/1303)` in your deployment as well

**Comment by TejasRGitHub** [comment]
Hi @SofiaSazonova , sure

**Comment by TejasRGitHub** [comment]
Hi @SofiaSazonova , I have tested the PR on my data.all instance. Looks good from the usability perspective

Testing Done - 

Created 100 consumption roles and checked if all consumption roles are loaded on request modal page ✅
