### ISSUE TITLE
Reject Reason should not be editable when the share is already approved 

### ISSUE THREAD

**Issue by TejasRGitHub** [data-dot-all/dataall#1290]
**Is your idea related to a problem? Please describe.**
While rejecting a share, the dataset owner / steward can add in a rejection reason. 

When the dataset is approved, this field can still be updated and edited. 

**Describe the solution you'd like**
After the dataset is approved, the reject reason field should not be editable

*P.S. Don't attach files. Please, prefer add code snippets directly in the message body.*

**Comment by SofiaSazonova** [comment]
It's covered [in this PR](https://github.com/data-dot-all/dataall/pull/1277)
