### ISSUE TITLE
Error while fetching cognito groups

### ISSUE THREAD

**Issue by TejasRGitHub** [data-dot-all/dataall#1314]
### Describe the bug

With refactoring due to maintenance window change, the fetching of cognito groups is erroring out and creating issues. 
Below is the error thrown by the gql lambda.
```str.maketrans({'[': None, ']': None, ', ': ','})
ValueError: string keys in translate table must be of length 1
```

### How to Reproduce

Deploy data.all with v2.5 and with Cognito IDPenabled
Login into data.all. 
Check the gql logs

### Expected behavior

str.maketrans({'[': None, ']': None, ', ': ','}) -> Should not fail and should remove the [ , ] or the ', ' from the string

### OS

Mac

### Python version

3.9

### AWS data.all version

2.5

**Comment by noah-paige** [comment]
This is resolved as of #1315 - closing this issue + thank you @TejasRGitHub for the quick fix!
