### ISSUE TITLE
Security configuration for Glue crawler

### ISSUE THREAD

**Issue by mourya-33** [data-dot-all/dataall#1324]
### Describe the bug

Glue crawlers do not have any security configuration attached which is flagged by checkov as FAILURE with the error message below.

CheckID		: CKV_AWS_195
CheckName	: Ensure Glue component has a security configuration associated
File		: /dataall-dataset-bphz8d77.yaml:636-672
Resource	: AWS::Glue::Crawler.dataalld1bphz8d77crawler
Guideline	:<a href= "https://docs.prismacloud.io/en/enterprise-edition/policy-reference/aws-policies/aws-general-policies/ensure-aws-glue-component-is-associated-with-a-security-configuration"> CKV_AWS_195 </a>

### How to Reproduce

Run a checkov scan on the dataset template. The scan report will contain the entry mentioned above in the description.

### Expected behavior

Glue crawlers should have a security configuration.

### OS

Mac

### Python version

3.10

### AWS data.all version

2.5

**Comment by dlpzx** [comment]
Hi @mourya-33 , thanks for the issue. Security enhancements are always welcome. Do you plan to work on this issue?

**Comment by noah-paige** [comment]
Closing this issue as complete
