### ISSUE TITLE
new deployments fail to configure Cognito

### ISSUE THREAD

**Issue by petrkalos** [data-dot-all/dataall#1353]
### Describe the bug

In #1289 configuring cognito was moved from running after the deployment of Cloudfront to run after the deployment of the Cognito User Pool. The configuration script requires the [CloudfrontDistributionDomainName param](https://github.com/data-dot-all/dataall/blob/main/deploy/custom_resources/cognito_config/cognito_urls_config.py#L38) which is only available after the deployment of Cloudfront.

### How to Reproduce

Every new deployment that is using Cloudfront (internet facing without custom domain) will fail to deploy the backend.
Existing deployment won't fail because the SSM param already exists.

### Expected behavior

Internet facing depoyments without custom domains should be able to deploy without errors.

### OS

N/A

### Python version

N/A

### AWS data.all version

> e2b70cb85a4d8cfc3aafa04cbc5387f6d58b2e8e

**Comment by noah-paige** [comment]
This bug has been fixed as of #1366 

Closing this issue as completed!
