### ISSUE TITLE
Variable '$dashboardUri' of required type 'String!' was not provided.

### ISSUE THREAD

**Issue by ozggumus-aws** [data-dot-all/dataall#1381]
### Describe the bug

I am receiving this error when I try to start a session from the data.all UI: _Variable '$dashboardUri' of required type 'String!' was not provided._

### How to Reproduce

```
1) Go to Dashboard tab
2) Click Quicksight
3) Click Start Session
```

### Expected behavior

I was expecting a new tab to be open in quicksight console. 

### Screenshots

<img width="501" alt="Screenshot 2024-07-02 at 19 59 14" src="https://github.com/data-dot-all/dataall/assets/128488927/21b57043-2470-4cb6-857e-2767661aee72">

### OS

Mac

### Python version

python3.9

### AWS data.all version

v2.5.0

### Additional context

The first time I set up the environment I was able to use this. Today I updated my code to the latest version and reopened the data.all UI and start receiving this error.

**Comment by noah-paige** [comment]
Hi @ozggumus-aws - thank you for opening this issue. It looks like this is a bug specific to `getDashboardAuthorSession` that was introduced recently

I will open a PR with the associated fix and link it here for tracking
