### ISSUE TITLE
Revoked Dataset table is still available to the user in table preview

### ISSUE THREAD

**Issue by srisri97** [data-dot-all/dataall#1392]
### Describe the bug

For one of the table in "Shares", access has been **Revoked** and status updated to "**REVOKE_SUCCEEDED**".
<img width="1190" alt="Screenshot 2024-07-09 at 6 05 30 PM" src="https://github.com/data-dot-all/dataall/assets/175122111/b8dbf51b-3eb8-463a-8cb0-a675037d2128">

User, who had requested the share access, could access the same table data in Table preview,
even after "**REVOKE_SUCCEEDED**".
User following these steps to access revoked table: Environments -> DATASETS -> TABLE -> PREVIEW -> Revoked Table data is VISIBLE
<img width="1227" alt="Screenshot 2024-07-09 at 6 07 19 PM" src="https://github.com/data-dot-all/dataall/assets/175122111/af7a6c48-3abf-461e-ba09-7f61d35303eb">

BUG: Revoked table data should not be visible to user.

### How to Reproduce

1)From "Shares" section revoked access to a table
2)Wait till the status changed to REVOKE_SUCCEEDED
3)Log in as a user who has requested for the share access 
4)Go to Environments -> DATASETS -> TABLE -> PREVIEW -> Revoked Table data is VISIBLE

### Expected behavior

Revoked table data should not be visible to user.

### OS

Mac Sonoma 14.5

### Python version

3.8

### AWS data.all version

2.0.0

**Comment by dlpzx** [comment]
Hi @srisri97 thanks for opening the issue. This problem was already reported https://github.com/data-dot-all/dataall/issues/1173 and solved in https://github.com/data-dot-all/dataall/issues/1173. It was released as part of 2.5 https://github.com/data-dot-all/dataall/releases/tag/v2.5.0.
