### ISSUE TITLE
Incorrect database shown in worksheet for a shared database created on central catalog account

### ISSUE THREAD

**Issue by TejasRGitHub** [data-dot-all/dataall#1432]
### Describe the bug

After setting up a central catalog account based dataset as described here - https://github.com/data-dot-all/dataall/pull/1021 and creating a share on that dataset , the database name is incorrectly populated in the worksheet module for that dataset share. 

Instead of the database_shared , database-resource-link_shared is displayed. 

<img width="1631" alt="image" src="https://github.com/user-attachments/assets/3511199c-97c3-4d82-a825-afb9d9882f00">

### How to Reproduce

1. Create central catalog based dataset - Instructions here - https://github.com/data-dot-all/dataall/pull/1021#issuecomment-1917946904
2. Create a share with this dataset 
3. Create a worksheet 
4. Select appropriate env and check the drop down containing the name of the table., it should be the resource_link_shared instead of database_shared

### Expected behavior

Should display the correct database name i.e. database_shared

### OS

Mac

### Python version

3.9

### AWS data.all version

2.6

**Comment by noah-paige** [comment]
Thanks @TejasRGitHub  for fililng this issue and looking into a fix - will take a look at the associated PR and leave any additional comments
