### ISSUE TITLE
Invalid documentation

### ISSUE THREAD

**Issue by zsaltys** [data-dot-all/dataall#1463]
### Describe the bug

https://data-dot-all.github.io/dataall/deploy-locally/ says to use branch:

`git clone https://github.com/data-dot-all/dataall.git --branch v2.6.0`

Such a branch does not exit

### How to Reproduce

NA

### Expected behavior

should provide accurate branch name.. or maybe use tags?  tags/v2.6.0 

### OS

NA

### Python version

NA

### AWS data.all version

NA

**Comment by noah-paige** [comment]
As per [Git Documentation](https://git-scm.com/docs/git-clone) on the `clone` command: 
```
--branch can also take tags and detaches the HEAD at that commit in the resulting repository.
```

I have found the same to be true in my use of the `git clone` command - please do let us know if you experience different behavior?

**Comment by zsaltys** [comment]
I can swear it wasn't working when I tried.. But I tried again now and it works fine.
