### ISSUE TITLE
Redirection for s3-datasets doesn't work correctly 

### ISSUE THREAD

**Issue by TejasRGitHub** [data-dot-all/dataall#1497]
### Describe the bug

If a user uses a link which is pointing to a specific resource in data.all and if the user is not logged in then the login page is displayed, once the user logs-in then they are taken to the specific resource. But for /s3-datasets this redirection fails 

### How to Reproduce

Goto any s3-dataset . 
logout 
Login with the same link pointing to the s3-dataset
Check if redirection works

### Expected behavior

Should be redirected to the s3-datasets page 

### OS

Mac

### Python version

3.9

### AWS data.all version

2.6

**Comment by SofiaSazonova** [comment]
Issue resolved with https://github.com/data-dot-all/dataall/pull/1494
