### ISSUE TITLE
Support for Aurora serverless 2

### ISSUE THREAD

**Issue by zsaltys** [data-dot-all/dataall#1513]
Aurora serverless 1 is getting deprecated and replaced by version 2. Data.all should switch to v2 which supports better autoscaling. We also need to figure out an upgrade procedure for those who are already deployed with version 1.

 https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/aurora-serverless-v2.upgrade.html#sv1-to-sv2-apg

I couldn't find official AWS EOL notice but I was told so on an AWS ticket and was able to find this: https://www.infoq.com/news/2024/01/aurora-serverless-v1-retirement/#:~:text=We%20are%20reaching%20out%20to,Serverless%20version%201%20(v1).

**Comment by dlpzx** [comment]
Hi @zsaltys , Thanks for opening the ticket, there is actually an issue already opened for this #548
