### ISSUE TITLE
Modal dialog to list users from Team names

### ISSUE THREAD

**Issue by rbernotas** [data-dot-all/dataall#1626]
**Is your idea related to a problem? Please describe.**

We have an internal change for which we would like to propose contribution in part.  Users would like to understand who is in the Teams, without having to access the separate roles based access system (Cognito or otherwise), for purposes of locating contacts for governors/stewards/owners/users of a dataset/share/env/org, so that they can contact individuals to ask questions or get support.

**Describe the solution you'd like**

The feature would turn various appearances of the Team names text throughout data.all, into clickable links that pop up a modal dialog showing the users in the Teams.

For default data.all this would use Cognito for looking up the users; for custom roles based access systems it would use that custom system (and need to be implemented by the admins of that data.all instance).

*P.S. Don't attach files. Please, prefer add code snippets directly in the message body.*

**Comment by rbernotas** [comment]
PR is available here:  https://github.com/data-dot-all/dataall/pull/1627

Since we don't have Cognito available to us, we could use some help with feedback and testing on the Cognito aspects of this change, if there is interest in accepting this contribution.

**Comment by noah-paige** [comment]
Closing as completed in #1627 - thanks for the contribution @rbernotas
