### ISSUE TITLE
Unable to view logs in ECS share manager logs with code from main 

### ISSUE THREAD

**Issue by TejasRGitHub** [data-dot-all/dataall#1680]
### Describe the bug

git clone / git merge code from main branch. 
Deploy and make a share 
The share logs do not appear to be present and only few log line are present. 

<img width="1406" alt="image" src="https://github.com/user-attachments/assets/e762dfba-9062-472c-a27a-c0ebc67351fe">

### How to Reproduce

```
*P.S. Please do not attach files as it's considered a security risk. Add code snippets directly in the message body as much as possible.*
```
git clone / git merge code from main branch. 
Deploy and make a share 
The share logs do not appear to be present and only few log line are present. 

### Expected behavior

Logs from the share manager's methods like `approve_share` or `revoke_share` should be present

### OS

Mac

### Python version

3.9

### AWS data.all version

main branch code

**Comment by noah-paige** [comment]
this is from latest code on `main` and not release branch correct? 

There is a recent PR that alters with log levels a bit for `prod_sizing`: `true` deployments : https://github.com/data-dot-all/dataall/pull/1662

Can you share what env variables are there for the share manger ECS task?

**Comment by TejasRGitHub** [comment]
Hi @noah-paige , 

This code is from the `main` branch. 

Here's the env variables from ECS. Hiding some custom variables we use
<img width="960" alt="image" src="https://github.com/user-attachments/assets/eb2e7d07-3b7d-48e3-b294-096c62612922">

**Comment by noah-paige** [comment]
2 things:
- Can you adjust `LOG_LEVEL` to `DEBUG` and re-run to see if it adjusts back to as expected
- Confirming for this deployment you set `prod_sizing` to `True` ?

**Comment by TejasRGitHub** [comment]
- Can you adjust LOG_LEVEL to DEBUG and re-run to see if it adjusts back to as expected ( I tried adding this but this didn't work. I changed logger setting to what it was previously and it started to work again. 
<img width="1249" alt="image" src="https://github.com/user-attachments/assets/148964a3-2803-4bfc-8e98-aec8dd3ce377">


- Confirming for this deployment you set prod_sizing to True ? Yes

**Comment by noah-paige** [comment]
@dlpzx - can you take a look at the above and provide some insight on the logging changes made?
