### ISSUE TITLE
Can't Paginate to view all Folders

### ISSUE THREAD

**Issue by noah-paige** [data-dot-all/dataall#288]
### Describe the bug

If I have 11 or more Folders in one Data All dataset I am not able to see more than the first 10 and can not click to the next page to view any additional

This occurs when looking at the Folders Table in the Data Tab view when clicking on a specific data.all dataset (additional -  I can search for the additional folders by name and they appear but can not click to retrieve the next page)

### How to Reproduce

```
*P.S. Please do not attach files as it's considered a security risk. Add code snippets directly in the message body as much as possible.*
```

1. Create a dataset in data all and add 11 or more folders
2. scroll to the Folders Table under the Data tab of the dataset --> attempt retrieve the next page of folders information

### OS

n/a

### Python version

n/a

### AWS data.all version

v1.3.1

**Comment by anmolsgandhi** [comment]
Hi @noah-paige is this issue this applicable in v2.2+? i see the version mentioned is v1.3.1.

**Comment by noah-paige** [comment]
Closing as complete in https://github.com/data-dot-all/dataall/pull/1158
