### ISSUE TITLE
Import of Dashboard / Dataset - Environment selection drop-down list is limited to 5 environments

### ISSUE THREAD

**Issue by gavclark** [data-dot-all/dataall#338]
### Describe the bug

When you are importing a dashboard or a dataset using the "Import" button:

![image](https://user-images.githubusercontent.com/16735754/222104391-62274a02-f769-47cc-aca4-2a6a32760d78.png)

You are prompted to choose the environment to import the dashboard into:

![image](https://user-images.githubusercontent.com/16735754/222104803-25f72118-6815-4426-8e40-80c726a9ca5e.png)

However when you use the drop down, only the first 5 environments are shown :

![image](https://user-images.githubusercontent.com/16735754/222105121-58afe560-7f0d-4802-b11a-c0267c13c1e5.png)

I have access to more than 5 environments and cannot import dashboards / datasets 

### How to Reproduce

```
*P.S. Please do not attach files as it's considered a security risk. Add code snippets directly in the message body as much as possible.*
```
You must have access to more than 5 environments (and belong to a team who is an admin of that environment / has the "manage dashboards" permission in that environment

Navigate to "dashboards" , choose the "import" option and use the drop-down selection list for environment - it will be limited to 5 environments

### Expected behavior

Should be able to import into any number of Environments where I am a member of the "admin" team of that environment , it should not be restricted to 5

### Your project

n/a

### OS

n/a

### Python version

3.8

### AWS data.all version

1.0

### Additional context

We really need to import these dashboards into our data.all environment and need a workaround ASAP

Please could you provide instructions if we can do this in the backend directly - perhaps by using the API's ?

**Comment by dlpzx** [comment]
Hi @gavclark, I will have a look to see if I can find the bug and fix it. Thank you for reporting it!

**Comment by gavclark** [comment]
Thanks a lot @dlpzx  :) 

I have a feeling the import function is to enable a way to create a record for the dashboard / dataset in the metadata database ? 

If that is the case, we could just insert the records directly into the metadata database for now rather than use the front end

For the time being, we've just reduced the number of environments someone has access to - so they can use the dashboard import function for a specific environment

**Comment by dlpzx** [comment]
Hi @gavclark this issue is solved in data.all >= 2.0.0, closing as completed!
