### ISSUE TITLE
UI Upgrade to Cloudscape & other customizations 

### ISSUE THREAD

**Issue by chamiles** [data-dot-all/dataall#347]
Very happy with the UI now looking at the next stage, curious if it would be in a good interest to migrate to cloudscape UI that is created, maintained, and used by the AWS console team. For customers writing new features in the future, the plugins and components would allow them to build rich user interfaces without having to add external packages. 

Curious to hear thoughts on this.

**Comment by ironspur5** [comment]
Also interested in hearing thoughts on using the Cloudscape components. https://cloudscape.design/demos/overview/

**Comment by dlpzx** [comment]
We will close this item as it is not a priority at the moment. It does not mean it is closed forever, if users show interest, we can open it again.
