### ISSUE TITLE
Unable to configure a share with an IAM Identity Centre role specified as the consumption role

### ISSUE THREAD

**Issue by nguforw** [data-dot-all/dataall#376]
### Describe the bug

I have a control tower environment and my users access the various accounts using permission sets / roles defined in IAM Identity Centre. So the ARN of these roles take the form of 
`arn:aws:iam::111111111111:role/aws-reserved/sso.amazonaws.com/eu-west-2/AWSReservedSSO_MyRoleName_2ra56c55a9f21hjk`

Whilst I am able to request and approve a share using this role as the consumption role, the shared items end up with a status of "SHARE_FAILED".

Looking at the share-manager logs I see the following:
`Failed to share table _mytable_ from source account 000000000000//eu-west-2 with target account 111111111111/eu-west-2due to: An error occurred (InvalidInputException) when calling the GrantPermissions operation: Invalid path for user, arn: arn:aws:iam::111111111111:role/AWSReservedSSO_MyRoleName_2ra56c55a9f21hjk`

### How to Reproduce

1. Configure a data share and specify a role that has been vended through IAM Identity Centre as the consumption role
2. Add some tables to the share
3. Submit the share
4. Accept the share from the data producer side.

### Expected behavior

The share should be successfully created

### OS

Windows

### Python version

N/A

### AWS data.all version

1.4.1

**Comment by dlpzx** [comment]
Hi @nguforw, thanks for opening this issue. You've got an interesting case here! Have you tried using `arn:aws:iam::111111111111:role/aws-reserved/sso.amazonaws.com/eu-west-2/AWSReservedSSO_MyRoleName_2ra56c55a9f21hjk` as the consumption role arn? or are you adding `arn:aws:iam::111111111111:role/AWSReservedSSO_MyRoleName_2ra56c55a9f21hjk` directly?

**Comment by nguforw** [comment]
@dlpzx - The consumption role was indeed defined using `arn:aws:iam::111111111111:role/aws-reserved/sso.amazonaws.com/eu-west-2/AWSReservedSSO_MyRoleName_2ra56c55a9f21hjk` and data.all was happy to accept this. The problem occurs further downstream when it is trying to configure the LakeFormation permissions to grant access to the various tables. My guess is that something is splitting the ARN up to get the role name and then further down in the process, there is an attempt to reconstruct the ARN but this is not taking into consideration the "unusual" structure of IIC role ARNs.

**Comment by anmolsgandhi** [comment]
#695

**Comment by anmolsgandhi** [comment]
@dlpzx @noah-paige is this still an issue we need to fix in v2.2+ ? I see the version being used here is 1.4.1.

**Comment by dlpzx** [comment]
This issue was solved by https://github.com/data-dot-all/dataall/pull/749
