### ISSUE TITLE
Add parameter to show data.all current version

### ISSUE THREAD

**Issue by dlpzx** [data-dot-all/dataall#377]
**Is your idea related to a problem? Please describe.**
I do not like going to the commits and looking for the release dates to establish the version of data.all that I currently have deployed. 

**Describe the solution you'd like**
I would like to look up this information in a more straight forward way. For example we could implement an base file or an SSM parameter to keep this information.

*P.S. Don't attach files. Please, prefer add code snippets directly in the message body.*

**Comment by noah-paige** [comment]
Closing this issue as it has been implemented in PR #991
