### ISSUE TITLE
Invite team in the environment is not listing all the groups that I am part of in AD Idp

### ISSUE THREAD

**Issue by mvidhu** [data-dot-all/dataall#417]
### Describe the bug

I am trying to invite other team (AD group) to my environment in Data.All, however I cannot see the groups that I am part of since they are not in Cognito groups.
Since our organization is using Azure AD for authentication, we expect to see the AD groups also as part of the environment invite functionality.

### How to Reproduce

```
*P.S. Please do not attach files as it's considered a security risk. Add code snippets directly in the message body as much as possible.*
```
Integrate data.all with AD using Azure AD integration steps.
If you are part of multiple groups, you can see the custom.saml.groups in cognito showing list of groups.
Navigate to Data.All environments and try to invite a team you are part of. Dropdown only shows cognito group and does not integrate with AD teams.

### Expected behavior

We should be able to invite a different team from AD groups.

### OS

Mac

### Python version

3.11

### AWS data.all version

0.5.0

**Comment by anmolsgandhi** [comment]
@noah-paige i believe we now support other IDPs as of 2.x version? can we close this?

**Comment by noah-paige** [comment]
Yes this should be resolved and list groups should appear appropriately as of v2.2 with the PR - https://github.com/data-dot-all/dataall/pull/897

This requires the data.all admin team to configure data.all to work with a custom IdP (non-Cognito) - there are detailed instructions for how one can configure data.all in this way in [data.all's Documentation Pages Deploy to AWS Steps](https://data-dot-all.github.io/dataall/deploy-aws/)- _**Section 6.1 (Important) - Configure data.all to use external Idp**_

**Comment by noah-paige** [comment]
I will close this issue by EOD today since it is implemented in the latest data.all - please let me know if any other questions or concerns and thanks for opening up this issue!

**Comment by dlpzx** [comment]
Closed due to inactivity. If any support is needed do not hesitate to open a new issue.
