### ISSUE TITLE
Enforce Session Timeout on UI

### ISSUE THREAD

**Issue by manjulaK** [data-dot-all/dataall#421]
It is important that the UI times out after a preconfigured session limit (set in cdk.json). Current behaviour is that when refreshed a new session is started and user continues to be active . This is true for the all versions of data.all

**Comment by dlpzx** [comment]
Hi @manjulaK, thanks for raising the issue. For reference here is some more detail on the issue: when a user logs in to data.all UI the authentication tokens provided last for 1h before they expire. If the user then refreshes the UI page, we request a new token, but the user does not need to log in again.

For security, we would like to force the logout of the user after the session has timed out. We will need to review the current implementation (`frontend/src/hooks/useToken.js`)
