### ISSUE TITLE
Dataset glue profiling job security configuration

### ISSUE THREAD

**Issue by manjulaK** [data-dot-all/dataall#436]
### Describe the bug

Any profiling glue job created by data.all should have a security configuration attached with it. This is a security best practice. This should be reflected in the CFT.

### How to Reproduce

```
*P.S. Please do not attach files as it's considered a security risk. Add code snippets directly in the message body as much as possible.*
```

### OS

unix

### Python version

3.1

### AWS data.all version

v1.3,v1.4,v1.5

**Comment by dlpzx** [comment]
@noah-paige is this issue solved by #https://github.com/data-dot-all/dataall/pull/1434 ?
