### ISSUE TITLE
Limit Environment Roles permissions

### ISSUE THREAD

**Issue by alopezlopez4** [data-dot-all/dataall#462]
Is your idea related to a problem? Please describe.
After analyzing IAM roles in data.all we noticed that the IAM roles created as part of the environment stack has some permissions that are too open.

Describe the solution you'd like
Review and harden permissions for Environment roles

P.S. Don't attach files. Please, prefer add code snippets directly in the message body.

**Comment by noah-paige** [comment]
Closing issue - implemented in v1.6
