### ISSUE TITLE
Generic way to toggle data.all features

### ISSUE THREAD

**Issue by blitzmohit** [data-dot-all/dataall#473]
**Is your feature request related to a problem? Please describe.**
I'm trying to turn off certain features that are not needed in our instance of data.all

**Describe the solution you'd like**
Ability to turn off/disable features via a single configuration, with support for the following features:

1.  Pipelines
2. ML Studio
3. Notebooks
4. Worksheets

For the implementation it should include the following:

- Documented set of features that can be toggled
- Ability to toggle stacks, i.e. if the feature is disabled the related stack is not created
- Ability to toggle Backend APIs
- Ability to toggle Frontend UI components

**Comment by dlpzx** [comment]
Hi @blitzmohit, this task is tackled in the modularization work that is on-going for the backend and frontend.

From your points:

- Documented set of features that can be toggled --> not yet, we will finish the modularization and then we will document every module. 
- Ability to toggle stacks, i.e. if the feature is disabled the related stack is not created --> part of backend modularization
- Ability to toggle Backend APIs --> part of backend modularization
- Ability to toggle Frontend UI components --> part of frontend modularization

Here is a list of PRs where this work has been done or is in progress:
- backend modularization initial PR - #359 
- frontend modularization plan - #411 
- frontend enable/disable - #415 

- Notebooks backend modularization - #359
- Notebooks frontend modularization - #414 
- Dataset backend modularization - #413 , #432 , #440 , #441 
- Worksheets backend modularization - #449 
- MLStudio backend modularization - #448 
- Pipelines backend modularization - #457

**Comment by blitzmohit** [comment]
Thanks @dlpzx for sharing the detailed list. As discussed I am using the modularization-main branch now.

For toggling of features inside the backend modules, I have been testing with a decorator similar to ones defined in permission_checker, this would read the property specified from the global config (dataall.core.config) and can be added to specific resolvers we need to disable. 

@noah-paige @dlpzx Please share your thoughts on the approach & any other recommendations on how feature toggling would work inside the modules or even core if needed.

**Comment by noah-paige** [comment]
The above issue is addressed in the following PRs:
- https://github.com/data-dot-all/dataall/pull/538
- https://github.com/data-dot-all/dataall/pull/817

Closing this issue as complete!
