### ISSUE TITLE
Missing pages/images referenced in documentation 

### ISSUE THREAD

**Issue by InasK6** [data-dot-all/dataall#516]
### Describe the bug

On main branch 
**pictures**: missing documentation/userguide/docs/pictures/boot_qs_3.png referenced at documentation/userguide/docs/environment.md and documentation.png referenced at documentation/userguide/README.md
**links**: missing referenced html (understanding-data.html , collaborating-data.html ) pages at documentation/userguide/docs/index.md

### How to Reproduce

click on the links on the .md files on Github

### Expected behavior

access to referenced files when going to the given link in the .md files

### Screenshots

<img width="1160" alt="Capture d’écran 2023-06-13 à 10 51 16" src="https://github.com/awslabs/aws-dataall/assets/47898937/049c2f3c-38bc-423e-ba6c-4931b05b4858">
<img width="1173" alt="Capture d’écran 2023-06-13 à 10 51 05" src="https://github.com/awslabs/aws-dataall/assets/47898937/8828a604-66ef-4753-8e60-899e884f5e6a">
<img width="1101" alt="Capture d’écran 2023-06-13 à 10 50 51" src="https://github.com/awslabs/aws-dataall/assets/47898937/76eb36ac-e7d9-4409-bb8e-6122b4c9b402">
<img width="1176" alt="Capture d’écran 2023-06-13 à 10 50 20" src="https://github.com/awslabs/aws-dataall/assets/47898937/ada4b7ec-398b-4aab-9b2d-4e809049139a">

### OS

macos

### Python version

3.9.6

### AWS data.all version

v1.6.0

**Comment by dlpzx** [comment]
@InasK6 thanks for raising the issue, we will fix it as soon as possible :)

**Comment by dlpzx** [comment]
already solved
