### ISSUE TITLE
HealthOmics module in "Play" tools

### ISSUE THREAD

**Issue by dlpzx** [data-dot-all/dataall#563]
I want to use HealthOmics in a more ready-to-use solution and use it alongside data.all as a new "Play" tool

**Describe alternatives you've considered**
Credits to @ironspur5 that started the design drafts. I added some comments here:

![image](https://github.com/awslabs/aws-dataall/assets/71252798/cf07d6c9-9b05-4d36-855e-74a1fbc1f4e7)

**Additional context**
It is designed to be part of the modularization repo structure

**Comment by dlpzx** [comment]
@ironspur5 I just rebased the branch and did some changes to it that will help you in implementing the above design

**Comment by zsaltys** [comment]
@dlpzx could we add more information here what is Omics, what problem it helps solve etc?

**Comment by ironspur5** [comment]
Hello @zsaltys Omics, now called HealthOmics, is an AWS service that helps users such as bioinformaticians and/or researchers to process and generate insights from genomics and other biological data stored in the cloud. Raw genomic data can be sent to a HealthOmics managed workflow and then stored in a manageable format for querying/visualizing/sharing. For health/life sciences Data.all users, this would a welcome feature, similar to the existing integration with SageMaker Jupyter notebooks.
