### ISSUE TITLE
Handle exceptions on revoking share objects 

### ISSUE THREAD

**Issue by arjun-chopra** [data-dot-all/dataall#584]
If the consumption role is changes in certain cases, these roles are destroyed and recreated. This breaks the sharing done by data.all with the consumption role. While revoking these shares, the revoke fails with exception that there are no access rights. It's easier to add exception handling and allow revoke to go through, as these rights were already revoked by lakeformation automatically.

**Comment by dlpzx** [comment]
Hi @arjun-chopra thanks for raising the issue. At the moment it is not prioritized but we can support you in the implementation. From what you are describing it would be sufficient with some changes to the exception handling in the revoke actions. Let us know what is your point of view and if you need more support in implementation

**Comment by dlpzx** [comment]
This was solved by #485
