### ISSUE TITLE
Standardize core modules and cleanup dead code

### ISSUE THREAD

**Issue by dlpzx** [data-dot-all/dataall#741]
**Is your idea related to a problem? Please describe.**
Data.all V2 modules in the backend follow a particular structure. Division of resolvers, db, services... At the moment core modules such as environments and organizations follow the old structure. In addition, there dead code in core that has not been removed.

Additionally, some of the operation names on the front end are to be changed to a standard naming convention (i.e. camel case, matching with backend name, etc.)

**Describe the solution you'd like**
Clean code that follows the same standard

*P.S. Don't attach files. Please, prefer add code snippets directly in the message body.*

**Comment by dlpzx** [comment]
Completed

**Comment by dlpzx** [comment]
Some modules are still note refactored, re-opening issue:
- environments
- groups
- permissions
- stacks

**Comment by SofiaSazonova** [comment]
- [ ] environments 
- [ ] groups https://github.com/data-dot-all/dataall/pull/1113
- [ ] permissions
- [ ] stacks

**Comment by dlpzx** [comment]
@SofiaSazonova the only thing left in this issue is refactoring environment resolvers right?

**Comment by anmolsgandhi** [comment]
Hi @SofiaSazonova can this issue be closed ?

**Comment by dlpzx** [comment]
Completed in 2.5.0
