### ISSUE TITLE
Integration with Keycloak IDP

### ISSUE THREAD

**Issue by mvidhu** [data-dot-all/dataall#770]
### *P.S. Don't attach files. Please, prefer add code snippets directly in the message body.*

We are setting up keycloak as IDP with user federation to Azure AD. We would like to know if Data.all supports keycloak IDP for authentication & authorization of users?

**Comment by dlpzx** [comment]
Hi @mvidhu, sorry for the late response. Let me understand the situation, do you want to replace Azure AD by Keycloak or would it be an add-on on top of your existing Azure AD server?

For the first situation, from what I am reading in the keycloak docs it allows SAML integration, the [cognito docs](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-saml-idp.html) and this [medium post](https://awskarthik82.medium.com/how-to-add-keycloak-as-saml-identity-provider-in-aws-cognito-f091ec550dd7).

One example that looks very similar to what we would need to do to integrate keycloak with Cognito is what they do in AWS [Orbit Workbench](https://awslabs.github.io/aws-orbit-workbench/keycloak-integration)

**Comment by mvidhu** [comment]
Sorry for the delay in response. We would like keycloak to be add-on top of our existing Azure AD setup.
We want to use keycloak as IDP with authentication federated to Azure AD. We can discuss more over a meeting.

**Comment by dlpzx** [comment]
Hi @mvidhu, it is never too late :) [Release 2.2.0](https://github.com/data-dot-all/dataall/releases/tag/v2.2.0) includes a [feature](https://github.com/data-dot-all/dataall/pull/897) that replaces Cognito completely with your own IdP. It allows more flexibility on how the user information from authentication is retrieved and used for authorization. Take a look at the PR and docs (in deployment guide) and let's have a call to deep dive on your issue.

**Comment by noah-paige** [comment]
Hi all - giving notice that this issue is planned to be closed tomorrow due to inactivity. Please let us know if you need any other assistance on the above @mvidhu and happy to continue conversation.

Otherwise, thanks for raising this issue!

**Comment by noah-paige** [comment]
Closing the above issue - please re-open or file a new issue if any additional comments/concerns, thanks!
