### ISSUE TITLE
S3 buckey key policy for CI bucket in multi-account deploy is missing permissions for infra account

### ISSUE THREAD

**Issue by rbernotas** [data-dot-all/dataall#777]
### Describe the bug

When deploying data.all in a multi-account deploy (one CI account, one infra account), the S3 bucket key policy for the CI bucket is missing the infra account permissions.  We are having to add these permissions manually with every deploy, and each new deploy wipes out our changes to include the infra account.  This is even after re-bootstrapping both CI and infra accounts.  Present in 2.0.

Bucket name in CI account like "<resource_prefix>-<branchname>-ci-<resource_prefix><branchname><uuid>"

The key policy for this bucket looks like:

`
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "AWS": "arn:aws:iam::<CI_ACCOUNT_ID>:root"
            },
            "Action": "kms:*",
            "Resource": "*"
        },
        {
            "Effect": "Allow",
            "Principal": {
                "AWS": "arn:aws:iam::<CI_ACCOUNT_ID>:role/<DEPLOY_ROLE>"
            },
            "Action": [
                "kms:Decrypt",
                "kms:DescribeKey"
            ],
            "Resource": "*"
        }
    ]
}
`

It is missing the following from the key policy for a multi-account deploy, and the CodePipeline deploy will fail at various stages because the infra account doesn't have permissions here:

`
        {
            "Effect": "Allow",
            "Principal": {
                "AWS": "arn:aws:iam::<INFRA_ACCOUNT_ID>:role/<DEPLOY_ROLE>"
            },
            "Action": [
                "kms:Decrypt",
                "kms:DescribeKey"
            ],
            "Resource": "*"
        }
`

### How to Reproduce

Deploy data.all 2.0 with a multi-account deploy.

### Expected behavior

The deploy should succeed without manual intervention to add the key policy permissions to add the infra account.

### OS

n/a

### Python version

n/a

### AWS data.all version

2.0

**Comment by noah-paige** [comment]
Hi @rbernotas - thanks for raising this issue. I have tried to replicate the above in my own cross-account deployment of data.all but can not seem to replicate at the moment

The bucket mentioned above is the "artifacts bucket" that is created by CDK CodePipeline construct ([CDK docs](https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.pipelines/CodePipeline.html))

In the `pipeline.py` file around L127 we create this CodePipeline: `self.pipeline = pipelines.CodePipeline(...)` which should have nothing specified for `artifacts_bucket` parameter (meaning CDK will create for us) but does have `cross_account_keys=True`

I would ask if you could validate the above is the same in your deployment?

It is also strange why this would come back on every deploy even after you change the key policy - was this issue only being seen in 2.0 or earlier versions of data.all as well?

**Comment by rbernotas** [comment]
Yes, we have cross_account_keys=True in pipeline.py, we haven't changed that.  This has generally happened since we moved to multi-account deploys.  This makes me think that our account processes are disallowing key policies from having cross-account configuration, I will check.

**Comment by noah-paige** [comment]
Hi @rbernotas - were you able to confirm if this is an issue particular to your account processes rather than a bug in data.all? 

Planning to close this issue shortly unless additional work is pending, do let me know

**Comment by rbernotas** [comment]
@noah-paige , this can be closed, it is due to our account processes, not a bug in data.all.
