### ISSUE TITLE
Git release stage CICD Pipeline Multiple Runs

### ISSUE THREAD

**Issue by noah-paige** [data-dot-all/dataall#802]
### Describe the bug

The git release stage (if enabled) results in multiple releases for 1 run of the CICD pipeline since it is editing the source repository in CodeCommit

When `git_release = true` results in mutiple releases for run of the CICD pipeline. Nothing is breaking, but it is a sub-optimal devops experience and may need to be re-designed it or removed

### How to Reproduce

* Set git_release to true in cdk.json
* Commit + Push changes to codecommit to start another run of CICD Pipeline
* The final step (releage-stage) should push changes to CodeCommit and start another run of CICD

### Expected behavior

* CICD runs only 1 time for a pushed change
    * Option 1 - Determine a method to not run the CICD Pipeline a second time if the change is coming from the release-stage CodeBuildStep
    * Option 2 - Deprecate the git_release feature 

### OS

N/A

### Python version

N/A

### AWS data.all version

2.0

**Comment by dlpzx** [comment]
Merged in #1042
