### ISSUE TITLE
Share Requestor can not view Dataset folders in UI even after share is complete

### ISSUE THREAD

**Issue by noah-paige** [data-dot-all/dataall#804]
### Describe the bug

When UserA is shared a dataset with all of its folders and clicks on the shared Dataset from the Dataset view

* UserA can not click on more information for the folders, receives the following error instead

 An error occurred (UnauthorizedOperation) when calling LIST_DATASET_FOLDERS operation: `User: XXXXX is not authorized to perform: LIST_DATASET_FOLDERS on resource: uri_here`

### How to Reproduce

* UserA requests access to a dataset including all of its tables and folders
* Dataset Owner approves the share request and share gets successfully processed
* UserA navigates to the Datasets Tab of the shared dataset and clicks on one of the folders it has been shared

### Expected behavior

UserA should be able to click on the Folder and receive some additional information related to the information (whether it should be the same amount of information as Dataset owner or a subset of that information is TBD)

### OS

N/A

### Python version

N/A

### AWS data.all version

2.0

**Comment by dlpzx** [comment]
I also noticed that in the table service the `DatasetTableService.get_table` should also be decorated with GET_TABLE permissions

**Comment by dlpzx** [comment]
Completed in #1163
