### ISSUE TITLE
Showing multiple shared dbs for same shared dataset for a single user in worksheets view

### ISSUE THREAD

**Issue by noah-paige** [data-dot-all/dataall#805]
### Describe the bug

A User (UserA) belongs to Group1, Group2, and owns consumption role (CR-1) all within EnvX. When all 3 Groups request access and get a share successfully approved to 1 Dataset (DatasetZ), UserA can see 2 shared DBs show but only 1 works querying the data in Worksheets 

* I believe this is because of filtering to the shared Datasets (in searchEnvironmentDataItems) is not filtering for the group that owns the worksheet so a shared DB is showing for both Group1 and Group2 but when querying the data it is using the role mapped to the group that owns the worksheet

### How to Reproduce

* Create EnvX with Owner Group1
* Invite Group2 and create a consumption role (CR-1) in EnvX
* Have UserA belong to Group1 and Group2
* Create a share request to a Dataset’s tables to Group1, Group2, and CR-1
* As UserA, create a new Worksheet and try to query data shared to UserA in EnvX
    * Multiple DBs should appear but not all will work

### Expected behavior

Only show 1 shared DB that is able to query data for the Group that owns the Worksheet

### OS

N/A

### Python version

N/A

### AWS data.all version

v2.0

**Comment by dlpzx** [comment]
This should be solved with #1063
