### ISSUE TITLE
Branches in step function

### ISSUE THREAD

**Issue by Shubhani-Pandey** [data-dot-all/dataall#837]
@dlpzx  @louishourcade Is there a possibility of creating branches in step functions using config file in DataAll. Eg:

![MicrosoftTeams-image (4)](https://github.com/awslabs/aws-dataall/assets/38568756/9e916647-c4d6-4c4d-9944-e4155d0fe646)

**Comment by dlpzx** [comment]
Hi @Shubhani-Pandey, thanks for opening an issue! We are not sure where exactly you want to create the StepFunctions, can you elaborate a bit more?

**Comment by Shubhani-Pandey** [comment]
@dlpzx  The above snapshot is a reference for what I want the step function to look like and I can create this as a standalone step function using AWS console but now, I want to re-create the same using DataAll config file i.e the DataAll deployed pipeline should give me a step function like this.  So far looking at the platform code, I am not able to create a config which would give me a flow like this (parallel branches) and my question is whether it is possible and how?

**Comment by dlpzx** [comment]
Hi @Shubhani-Pandey, sorry for the late response. From the way you are describing the issue I am assuming you moved from an old version of data.all to a more recent version and that you are using the data.all Pipelines feature. Data.all pipelines deploy a CICD pipeline with an initialized [DDK](https://awslabs.github.io/aws-ddk/) application (in current data.all version). 

Using DDK as a support constructs library on top of CDK gives us more flexibility in comparison with the config-wrapper approach. In this case, the construct from DDK for Step Functions is called `DataPipelines`, you can see an example of its usage in the [DDK example for databrew-athena](https://github.com/aws-samples/aws-ddk-examples/blob/main/databrew-athena/python/ddk_app/databrew_athena_stack.py#L297). Other examples are added in [DDK examples](https://github.com/aws-samples/aws-ddk-examples/). In addition, the [workshops and documentation](https://awslabs.github.io/aws-ddk/) are also very helpful resources to get started.

In case the DDK constructs do not fulfill your use-case, it is always possible to use CDK constructs directly.

**Comment by anmolsgandhi** [comment]
Since the question has been answered and there has been no further communication, we are closing this issue. Please feel free to reopen the issues if you have any more questions or require further assistance.
