### ISSUE TITLE
Docker containers run as root

### ISSUE THREAD

**Issue by zsaltys** [data-dot-all/dataall#864]
We have these Dockerfiles on the project:

/frontend/docker/prod/Dockerfile
/documentation/userguide/docker/prod/Dockerfile
/backend/docker/dev/Dockerfile
/compose/postgres/Dockerfile
/compose/elasticsearch/Dockerfile
/backend/docker/prod/ecs/Dockerfile
/backend/docker/prod/lambda/Dockerfile
/frontend/docker/dev/Dockerfile

All of these do not use a USER directive and run as root. Even though it's not always relevant it does trigger security scanners which Scan dockerfiles.

A simple solution is described here: https://www.geeksforgeeks.org/docker-user-instruction/

**Comment by dlpzx** [comment]
Hi @zsaltys, actually this issue was described by @manjulaK here: https://github.com/awslabs/aws-dataall/issues/445 We will re-pick it up and see if it needs to be prioritized.

**Comment by zsaltys** [comment]
@dlpzx we definitely want to prioritize this

**Comment by mourya-33** [comment]
PR - https://github.com/awslabs/aws-dataall/pull/895
