### ISSUE TITLE
Add capability on Data.all to allow changing the owner for a consumption role without deleting and recreating the role.

### ISSUE THREAD

**Issue by mourya-33** [data-dot-all/dataall#870]
**Is your idea related to a problem? Please describe.**
Data.all currently does not support any updates for the owners on the consumption role. For any change, the consumption role has to be deleted and recreated with the new owner association.

1. Navigate to Environments > Teams and add consumption role.
2. The role will prompt to select an owner from the drop down menu. Select an owner and click on "Add Consumption Role"

The role gets created. To re assign a different owner for the role, there is no provision to edit the consumption role. The only option currently is to delete the consumption role and recreate it by choosing the new owner from the drop down menu again.

**Describe the solution you'd like**
Add capability on the UI to allow the admins to edit the consumption role and map it to a different owner.

**Comment by dlpzx** [comment]
Hi @mourya-33, thanks for raising an issue. The fix is relatively easy to implement so we will try  to add it to our roadmap as soon as possible. In case you want to give it a try, let us know and we can indicate you how to start this feature.

**Comment by dlpzx** [comment]
We are currently working on it, PR will come shortly
