### ISSUE TITLE
Fix KMS key policy to now allow unrestricted access

### ISSUE THREAD

**Issue by zsaltys** [data-dot-all/dataall#878]
Checkov security scanner reports that this KMS key has a policy allowing access to anyone:

`"dataallstagingSNSkey6DB4ADCA": {
   "Type": "AWS::KMS::Key",
   "Properties": {
    "KeyPolicy": {
     "Statement": [
      {
       "Action": "kms:*",
       "Effect": "Allow",
       "Principal": {
        "AWS": {
         "Fn::Join": [
          "",
          [
           "arn:",
           {
            "Ref": "AWS::Partition"
           },
           ":iam::343184215156:root"
          ]
         ]
        }
       },
       "Resource": "*"
      },
      {
       "Action": [
        "kms:Decrypt",
        "kms:GenerateDataKey*"
       ],
       "Condition": {
        "StringLike": {
         "aws:SourceArn": {
          "Fn::Join": [
           "",
           [
            "arn:aws:ses:us-east-1:343184215156:configuration-set/",
            {
             "Ref": "dataallstagingSESConfigurationSetDE27A09B"
            }
           ]
          ]
         }
        }
       },
       "Effect": "Allow",
       "Principal": {
        "AWS": "*"
       },
       "Resource": "*"
      }
     ],
     "Version": "2012-10-17"
    },
    "EnableKeyRotation": true,
    "Tags": [
     {
      "Key": "Application",
      "Value": "dataall-staging"
     }
    ]
   }`

When synthesised with CDK this policy exists on:

/cdk.out/assembly-dataall-cdk-template-cicd-stack-dataall-staging-backend-stage/dataallcdktemplatecicdstackdataallstagingbackendstagebackendstackSesStack92E83825.nested.template.json#L89

In theory it could be OK that this policy is unrestricted but we should then review and make sure that all IAM roles that have access to this KMS key are restricted and then this violation can be skipped in the checkov scans.

**Comment by noah-paige** [comment]
The above is complaining about the default Key Policy that is added to the KMS Key that allows for all IAM users/roles in the account to perform KMS actions on this key (for the KMS Key attached to SNS in the SES Stack). 

I think we can restrict it by specifying the CDK Role (which creates/ manages the key) to have Admin permissions on Key and then allowing SES to push notifications to the Key

However, need to investigate if this would cause issues downstream for data.all admins who are trying to read notifications off the the SNS Topic to debug on email bounces/failures - may need to do some further review on what is the proper policy to add to this particular KMS Key

**Comment by zsaltys** [comment]
This KMS key is for sns topic for email bounces from sending emails within data.all.  We do not know in advance who may want to read this topic on their accounts. We would have to restrict this by asking for the roles in the configuration so that they could be applied to the key policy during deployment. I think it's a very low value issue and not worth the effort. We will file an exception to ignore this on our side and data.all can do the same when it supports checkov scans.
