### ISSUE TITLE
Add checkov security scanner to the build

### ISSUE THREAD

**Issue by zsaltys** [data-dot-all/dataall#881]
We should add checkov scanner and scan all CF templated and synthesized CDK templates to make sure there are no new violations.

**Comment by noah-paige** [comment]
Hi @zsaltys thanks for opening up this issue! We are checking with our team to ensure we can add Checkov as an additional GitHub workflow to have in place for all future PRs. 

We will get back to you shortly - I agree would be a good additional to the repo
