### ISSUE TITLE
Category in glossaries limited to 10?

### ISSUE THREAD

**Issue by weversonmuciarone** [data-dot-all/dataall#890]
Hi.

We have noticed that when creating categories under glossaries, seems to be a limitation for only 10 categories in one glossary.

Is this the case?

If yes, can we increase this number?

Thanks.

**Comment by weversonmuciarone** [comment]
Hi Noah, thanks for the reply.

Apologies I didn't specify the error correctly.

Dataall version - 1.5.5
![Cat List](https://github.com/awslabs/aws-dataall/assets/96920670/d088f2ef-1023-4487-915d-56e362f900ee)
![Glossary Label](https://github.com/awslabs/aws-dataall/assets/96920670/917dc218-1a0a-4c2f-9e64-34290909b847)
![Cat UI](https://github.com/awslabs/aws-dataall/assets/96920670/942d162e-1ba9-4633-b8fe-4c8b2ac968b9)


We can indeed create more than 10 Categories but they will not show in the UI.

Categories are limited to 10 in the UI as appear to be the case.

I will paste some snips here to illustrate my findings.

How can we get around this issue please?

**Comment by noah-paige** [comment]
He @weversonmuciarone - apologies for the delay in response time

My initial thought is that the query to list categories in the glossary is passing some type of limit, such as a `pageSize` if paginating the response, and then is not actually returning the complete set of categories within the glossary

I would check the query you are making to the backend to determine if that is the case and ensure that the query called is returning all categories without any pagination or limits to the response if that is the desired effect.

**Comment by weversonmuciarone** [comment]
I have found it Noah. Appreciated your help here.

This can now be closed.
