### ISSUE TITLE
Search returns results with very weak matches

### ISSUE THREAD

**Issue by zsaltys** [data-dot-all/dataall#926]
1. Let's imagine I have 3 datasets published in my data.all:

* test-iam-policy
* test-data
* best-data

2. If I search for test-iam-policy then data.all will return ALL 3 datasets in the search. This is because test-iam-policy matches completely, test-data has word test, and best-data has ending *est

3. I think returning first test-iam-policy and test-data is probably fine though I would argue that when I'm using - it should find the exact thing. Especially because the UI autocompletes the dataset for me so there's no need for it to return test-data too. And it should never return matches on partial words like best-data as that is simply confusing. Perhaps partial word search would be fine if it was searching if any of the words i searched appear fully in the text.. but if I search test it should not return anything that matches with "est".

**Comment by dlpzx** [comment]
Hi @zsaltys thanks for raising an issue, we will look into it. I have taken the liberty to edit the title and add tags to the issue.
