### ISSUE TITLE
Add support to reindex the catalog

### ISSUE THREAD

**Issue by zsaltys** [data-dot-all/dataall#929]
When we make changes to data.all and update ElasticSearch those changes are not atomic. There's always a possibility that that something can be changed on DB level but is never updated on the index. A proposal would be to have a graphql endpoint and a button DAAdmins could press which reindexes the whole catalog and removes any junk or orphaned records.

**Comment by dlpzx** [comment]
Hi @zsaltys thanks for raising this issue. I agree that currently there is no way of syncing RDS and ElasticSearch in data.all. It is a task that can be implemented in multiple ways, so I am going to throw some questions and options to discuss other alternatives before narrowing the design. A little of invent before we simplify.

What is the issue we are trying to solve?
1. Manual changes to RDS are not reflected in the OpenSearch cluster
2. Failure of certain dataset processes that result in mismatches between RDS and OpenSearch

**The task changes considerably depending on the issue we are trying to solve, for the next questions I have only taken into account issue 1**

Who should be able to access the functionality? 
1. DAAdmins (proposed above)
2. Developers with access the data.all infra account

How do we want to expose this functionality? 
1. As an API call that can be called from a button in the admins view (proposed above)
2. As an ECS task that is scheduled
3. As an ECS task that is executed on demand by developers with access the data.all infra account


Which database is the source of truth?
1. RDS

**Comment by dlpzx** [comment]
closing this issue in favor of #1078
