### ISSUE TITLE
Migrating from Manual PivotRole to Auto Create PivotRole Fails for v2.2

### ISSUE THREAD

**Issue by TejasRGitHub** [data-dot-all/dataall#943]
### Describe the bug

When setting the `enable_pivot_role_auto_create` to true and deploying data.all , the environment should be updated with a new pivot role `dataallPivotRole-cdk`. For environment which don't have datasets on them, this happens smoothly, but for environments which have datasets associated with them this stack update step fails. This is happening as the `ecs-role` is trying to assume the `dataallPivotRole-cdk` role which doesn't exist.

Also, in the update stack pipeline stage the environment stack is not updated for environment with datasets. 

### How to Reproduce

1. Deploy data.all with `enable_pivot_role_auto_create` to false.
2. Create an environment and create an imported dataset.
3. Deploy data.all with enable_pivot_role_auto_create` to true.
4. Now check if the environment CF is updated with dataallPivotRole nested stack
5. Goto UI -> Environment page and click `Update` in the Stacks tab.
6. Now the environment should be in CREATE_FAILED state

### Expected behavior

Update should work properly and the environment stack should contains the Nested PivotRole 

### OS

Mac

### Python version

3.9

### AWS data.all version

2.2

**Comment by noah-paige** [comment]
@TejasRGitHub - thanks for opening this issue and contributing the PR to resolve

The linked PR (above) has been merged - closing this issue as of now
