### ISSUE TITLE
Restricting Team/User Access to Worksheets

### ISSUE THREAD

**Issue by sandeephs1** [data-dot-all/dataall#945]
Team should only be allowed to query dataset via worksheet. Team is applied with Environment Permissions - `Create dataset Share requests for this environment` and `Run Worksheet Athena queries on this environment`

But it ends up with the below error 

`Insufficient permissions to execute the query. User: arn:aws:sts::123456789:assumed-role/<rolename> is not authorized to perform: lakeformation:GetDataAccess on resource: arn:aws:glue:usregion:5678912345:table/<tablename> because no identity-based policy allows the lakeformation:GetDataAccess action`

If team is added with the Env Permission `Create datasets on this environment`, user is able to query via worksheet but user can also create a dataset, which is not the requirement.

Any suggestion

**Comment by noah-paige** [comment]
Hi @sandeephs1 - thank you for opening this issue. You may have found a bug in the way we assign permissions for invited teams to an environment based on the set of env-level permissions given to the invited team.

I will try to reproduce the above scenario to ensure that I see the same behavior - from there can work on a fix

At a high level - the cause of the above is that we add a subset of glue and lakeformation permissiosn to the team's environment role in `/backend/dataall/modules/datasets/cdk/env_role_dataset_glue_policy.py` ONLY IF the team has the `CREATE_DATASET` permissions (which is the `Create datasets on this environment` Env Permission)

Removing that if statement will ensure the required permissions are added to the team's env role regardless of CREATE_DATASET or not
