### ISSUE TITLE
Consumer roles should be validated that they exist

### ISSUE THREAD

**Issue by zsaltys** [data-dot-all/dataall#949]
Currently anyone can register any string as a consumer role without any validation that it actually exists on an environments. This can lead to very confusing bugs. Here's a description of such a bug:

1) Create an environment name: foo
2) On environment foo register a role that exists on the aws account: arn:aws:iam::123:role/foo-role
3) Also register a role with the exact same name but make a mistake in the account id: arn:aws:iam::999:role/foo-role (at this point validation should reject adding such a role but there's no validation so it will be allowed)
4) Create a share request using role from step 3
5) The share will actually work because it will look for a role using code like this: 
```
principal_iam_role_arn = IAM.get_role_arn_by_name(
            account_id=self.target_environment.AwsAccountId,
            role_name=self.share.principalIAMRoleName
        )
```

6) The end result will be that the UI will say the share was filed for role: arn:aws:iam::999:role/foo-role but the actual permissions will be granted to role: arn:aws:iam::123:role/foo-role

Before you ask, yes this actually happened ;)

**Comment by zsaltys** [comment]
@noah-paige @dlpzx would be good to add IAM role validation into 2.3 if possible

**Comment by SofiaSazonova** [comment]
I took this. PR is on its way
