### ISSUE TITLE
ParameterStore throttling causes dataset stacks to fail to update

### ISSUE THREAD

**Issue by zsaltys** [data-dot-all/dataall#953]
### Describe the bug

Dataset stacks or any other stacks that need to mention the pivot role will make a call to parameter store to get the pivot role name. This can hit parameter store service limits and result in an error:

`An error occurred (ThrottlingException) when calling the GetParameter operation (reached max retries: 4): Rate exceeded`

This has happened to us and we have seen this error show up in the UI. This gets worse because I believe data.all is updating datasets periodically and if there's a lot of datasets it hits this limit quickly. What this causes is that the dataset stack fails to update because CDK cannot fetch the pivotRoleName and generates a role with a NONE like this:

`arn:aws:iam::123:role/None`

And then the dataset stack fails with an error like this for resource: DatasetAdminRoleBB509D11

`Resource handler returned message: "Invalid principal in policy: "AWS":"arn:aws:iam::123:role/None" (Service: Iam, Status Code: 400, Request ID: d789ec72-7463-4e84-8862-beeb08b54e37)" (RequestToken: 55adeab7-eb42-a25d-39c3-bf8ca965e6c9, HandlerErrorCode: InvalidRequest)`

### How to Reproduce

Push your ParameterStore to it's limits and attempt to update a dataset stack. Should also be able to do it if you have more than 40 datasets and run their updates all at the same time.

### Expected behavior

Default limits are here:
https://docs.aws.amazon.com/general/latest/gr/ssm.html

for GetParameter it's 40 calls per second. It is possible to put a parameter into higher throughput. To 10,000 per second. I think that could work for many....

Though the correct fix would be: don't run stack update if you're getting a throttle limit on GetParameter and instead hold back until you can generate the correct template. This should be done anywhere where CDK is trying to get anything from ParameterStore and use it in templates.

### OS

N/A

### Python version

N/A

### AWS data.all version

2.0

**Comment by dlpzx** [comment]
Hi @zsaltys thanks for opening an issue. It got me thinking, why do we need to read from SSM in the first place? We need it to know the pivot role name which is `dataallPivotRole` or `dataallPivotRole-cdk` (depending on the value of the cdk.json parameter `enable_auto_created_pivot_role`). The role name is used to define the role Arn to be assumed in SDK calls.

We have then some options to solve this issue:
1. Increase service quotas as you already pointed out
2. Define `enable_auto_created_pivot_role` feature in `config.json` including the role name. Read the name from `config.json` instead than from SSM
3. Modify ECS deployment task, set the pivot role name as environment variable, read env variable as fallback for SSM


In my opinion 2 is the most elegant solution, but I want to know if you see any drawbacks @noah-paige @zsaltys  @SofiaSazonova

**Comment by SofiaSazonova** [comment]
I tend more to option 3. It's more flexible solution for future. And we can use env. variables as a main resource, not as a fallback.

**Comment by zsaltys** [comment]
I got this error again. Here's the dataset stack logs from data.all UI on version 2.2:

```
Traceback (most recent call last):
  File "/dataall/base/cdkproxy/../../base/cdkproxy/app.py", line 68, in <module>
    CdkRunner.create()
  File "/dataall/base/cdkproxy/../../base/cdkproxy/app.py", line 63, in create
    instanciate_stack(stack_name, app, appid, env=env, target_uri=target_uri)
  File "/dataall/base/cdkproxy/stacks/manager.py", line 32, in instanciate_stack
    return cls(scope, id, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/jsii/_runtime.py", line 118, in __call__
    inst = super(JSIIMeta, cast(JSIIMeta, cls)).__call__(*args, **kwargs)
  File "/dataall/modules/datasets/cdk/dataset_stack.py", line 89, in __init__
    self.get_target_with_uri(target_uri=target_uri).description,
  File "/dataall/modules/datasets/cdk/dataset_stack.py", line 63, in get_target_with_uri
    engine = self.get_engine()
  File "/dataall/modules/datasets/cdk/dataset_stack.py", line 45, in get_engine
    engine = db.get_engine(envname=envname)
  File "/dataall/base/db/connection.py", line 114, in get_engine
    host = param_store.get_parameter(env=envname, path='aurora/hostname')
  File "/dataall/base/utils/parameter.py", line 56, in get_parameter
    raise e
  File "/dataall/base/utils/parameter.py", line 44, in get_parameter
    param_value = ssm.get_parameter(Name=pname)['Parameter']['Value']
  File "/usr/local/lib/python3.9/site-packages/botocore/client.py", line 514, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.9/site-packages/botocore/client.py", line 938, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ThrottlingException) when calling the GetParameter operation (reached max retries: 4): Rate exceeded
```

As you can see during the dataset create/update for some a call is made:  param_store.get_parameter(env=envname, path='aurora/hostname') trying to get aurora hostname?

@dlpzx do you know what is happening here? Is it just trying to connect to aurora and tries to get the hostname?

**Comment by zsaltys** [comment]
@dlpzx also to confirm we are using auto created pivot role and this issue is still happening.

**Comment by dlpzx** [comment]
Hi @zsaltys I am picking up this issue. Before doing any architectural changes, we can use SSM as we currently do but using Higher Throughput. I wanted to check the [pricing](https://aws.amazon.com/systems-manager/pricing/) to verify the related costs: `$0.05 per 10,000 Parameter Store API interactions`, which are pretty assumable.

I would recommend to follow [this steps](https://docs.aws.amazon.com/systems-manager/latest/userguide/parameter-store-throughput.html#parameter-store-throughput-increasing) in the AWS backend account and the problem should be strongly alleviated.

Do you think we should still implement other types of guardrails?

**Comment by zsaltys** [comment]
@dlpzx No additional guardrails are needed I think. Let's just make sure that data.all creates **Higher Throughput** keys by **default** because it really does not seem expensive to me. Do you know if you fix this and we deploy a new version will CF be able to upgrade our existing SSM params to higher throughput? If not then we need some sort of migration script to run during deployment.

**Comment by dlpzx** [comment]
Hi @zsaltys, from what I understood in the documentation it is not a setting of the parameter but of the account/region. So if we set the account/region settings to a higher throughput, it affects all parameters without needing to update the parameters.

<img width="1674" alt="image" src="https://github.com/data-dot-all/dataall/assets/71252798/a0872174-12f3-436e-ae6c-cb0ba7aec366">

We do not need a migration script. The only thing that we could automate is the configuration of the settings, but I am not 100% sure it is needed: 1. not everyone is running into this issue, 2. it is 2 clicks to change this setting if the limit is reached so the automation does not save us a lot of effort. What do the rest think? @noah-paige @petrkalos @SofiaSazonova

**Comment by zsaltys** [comment]
@dlpzx I don't understand how not everyone runs into this issue. Can we test?

Can you create 50 datasets and then force the background dataset update script to run? Then check the dataset UI how many datasets show as failed.

I am pretty sure you will run into this issue easily. I don't think it's acceptable that users need to then find out on their own that they need to navigate to ParameterStore and click some button.

**Comment by dlpzx** [comment]
Hi @zsaltys thinking long-term and based on your feedback we have decided to implement more support for ParameterStore, not only recommendations and docs. 

For `prod_sizing=True` environments we can implement a custom resource that executes the following API call`aws --region "$REGION" ssm update-service-setting --setting-id "arn:$AWS_PARTITION:ssm:$REGION:$ACCOUNT_ID:servicesetting/ssm/parameter-store/high-throughput-enabled" --setting-value true` and updates the Account settings of the central infrastructure account.

**Comment by noah-paige** [comment]
We have implemented a way to enable SSM high throughput setting as part of enabling `prod_sizing`  as `True` in the `cdk.json`

We do so using a custom resource (since no CDK construct allows us to set this SSM setting) in this PR #1154 

For now I will be closing this issue as the fix is implemented. Please take a look at the PR and let us know if any questions or concerns - happy to re-open or file a new ticket if additional comments arise!
