### ISSUE TITLE
Local dev environment is broken after recent changes

### ISSUE THREAD

**Issue by anushka-singh** [data-dot-all/dataall#957]
### Describe the bug

Local dev environment is broken
When you try to go to http://localhost:8080/console/shares, you will see this error:
<img width="1720" alt="Screenshot 2024-01-05 at 11 22 02 AM" src="https://github.com/data-dot-all/dataall/assets/26413731/061ecd86-a418-45d1-87fd-d1b647a89522">

### How to Reproduce

```
When you try to go to http://localhost:8080/console/shares, you will see this error as shown in the screenshot
```

### OS

Mac

### Python version

3.8

### AWS data.all version

2.2

**Comment by noah-paige** [comment]
Closing this issue as resolved in #967 - thanks for opening and contribution @anushka-singh @TejasRGitHub
