### ISSUE TITLE
Glue table not visible after upgrading to v2.2 with enable auto created pivot role

### ISSUE THREAD

**Issue by TejasRGitHub** [data-dot-all/dataall#979]
### Describe the bug

While updating data.all to v2.2 with enable auto created pivot role enabled , the pivot role is not formed ( this is fixed in https://github.com/data-dot-all/dataall/pull/948 ) 

Due to this failure, at the time of updating the dataset stacks , zero (0) glue tables fetched by the tables_syncer.py. This causes the `LastGlueTableStatus` set to `Deleted`. 

Once the pivotRole was corrected and the ECS task for tables syncing is running ( i.e. the tables_syncer.py ), the glue tables are fetched but the `LastGlueTableStatus` is not updated to `InSync` . 

Due to this, even though the glue tables exists for the dataset on the AWS account, they are not displayed on the UI. 

### How to Reproduce

1. Create a dataset with glue tables 
2. Query those tables in `DatasetTables` table and update the `LastGlueTableStatus` to `Deleted`
3. Check the UI if those tables are not present. 
4. Sync the tables, and check the logs, the tables would be fetched from glue but the `LastGlueTableStatus` is not updated to `InSync`

### Expected behavior

After tables_syncer.py is running or click on the Synchronize button on the UI, the tables should be properly updated in the RDS with `InSync` status if they are fetched from the glue boto3 call  

### OS

Mac

### Python version

3.9

### AWS data.all version

2.2

**Comment by dlpzx** [comment]
I have seen the PR and it is currently being tested. Great catch, thanks for picking it up

**Comment by noah-paige** [comment]
Resolved in PR #980 - closing this issue now
