### ISSUE TITLE
Default networking setup created when creating a new environment can be surfaced in the Admin UI

### ISSUE THREAD

**Issue by awskaran** [data-dot-all/dataall#982]
**Is your idea related to a problem? Please describe.**
when a new environment is created, it creates a VPC with 3 public and 3 private subnets in the target account. These network constructs are not surfaced in the UI and as such Admins and Users might not have visibility into existing network resources they can use for things like creating a Notebook.

**Describe the solution you'd like**
Under Admin > Environments > {SPECIFIC_ENV} > Environments tab
the VPC and subnets should be surfaced automatically as Environment VPC

**Comment by dlpzx** [comment]
Hi @awskaran, I understand your confusion, maybe we can do a better work at simplifying the Environment tabs. 
- data.all Environment creates VPC infrastructure as part of the creation of ML Studio domain. It is visible in the ML Studio Domain tab
![Screenshot 2024-01-18 at 14 28 36](https://github.com/data-dot-all/dataall/assets/71252798/92732acd-5707-4f78-9937-ef2e2f859eb4)

Notebooks are not necessarily related to ML Studio Domain, the VPC for ML Studio might not be used by Notebooks. For VPCs that can be used for Notebooks we have the Networks tab, where we can add VPC details that can later be used in the creation of Notebooks.  It does not create VPCs, it only registers its metadata.

![Screenshot 2024-01-18 at 14 31 34](https://github.com/data-dot-all/dataall/assets/71252798/be019f6b-917e-4ad5-ae13-f2e52d1b6c35)


Here are some ideas that could prevent the confusion. Let me know which ones sound interesting:
- rename "Networks" tab to "Notebooks"
- if data.all creates or uses a VPC for MLStudio, add it automatically to "Networks"/"Notebooks"

**Comment by awskaran** [comment]
I think the second point looks more promising from end user perspective `if data.all creates or uses a VPC for MLStudio, add it automatically to "Networks"/"Notebooks"` 
I would like to use the already created VPC. Although I have concern that the VPC CIDR by default is /16 and the private subnet cidr is /24 so the address space is small in private subnet which is most likely to be used for notebook creation 
can we change the subnet mask as well for the private subnet as part of this change or should that be a different issue?

**Comment by dlpzx** [comment]
Hi @awskaran, I think we could increase the CIDR range of the subnets created for the VPC, maybe instead of /24 we could have /20. I am concerned for the backwards compatibility of this feature. We need to test how is the VPC affected in IaC with this changes and if it affects the ML Studio domain. We can start by adding the VPC to the registered networks and then see if we can edit the VPC.

**Comment by dlpzx** [comment]
This issue will be closing soon as it has been stale for a long time
