### ISSUE TITLE
Network drop down selection on Notebook creation page

### ISSUE THREAD

**Issue by awskaran** [data-dot-all/dataall#983]
**Is your idea related to a problem? Please describe.**
When creating a notebook from the UI, user needs to add a VPC ID and Subnet ID which if not communicated by the admin is difficult for users to get hold off unless they have access to AWS console and understand how to navigate it.

**Describe the solution you'd like**
I want the UI to present me with a drop down selection of VPC ID and Subnet IDs while creating the Notebook, once I have made the Environment selection on the Deployment pane.
The UI should make the options available based on the network setup added at the Environment level.
Ideally the subnet list should be restricted to private subnets

*P.S. Don't attach files. Please, prefer add code snippets directly in the message body.*
![image](https://github.com/data-dot-all/dataall/assets/94186001/ca78ffd1-22b0-4938-8fd4-982968601748)

**Comment by dlpzx** [comment]
Hi @awskaran, I found the issue! It is a small bug introduced with v2 changes. We will fix it as soon as possible. Thanks for pointing it out.

**Comment by enr0c** [comment]
Great:) This one was bothering me as well;) I thoughts it has been a feature rather than a bug, but now that its fixed, i am looking very much forward to it!
