### ISSUE TITLE
remove AllowAllToAdmin statement from bucket policies

### ISSUE THREAD

**Issue by zsaltys** [data-dot-all/dataall#997]
Currently when a share is created for an S3 bucket (using bucket policies) data.all will add the following statement to the bucket policy:

```
{
			"Sid": "AllowAllToAdmin",
			"Effect": "Allow",
			"Principal": "*",
			"Action": "s3:*",
			"Resource": [
				"arn:aws:s3:::BUCKET_NAME",
				"arn:aws:s3:::BUCKET_NAME/*"
			],
			"Condition": {
				"StringLike": {
					"aws:userId": [
						"ROLE_ID_DATASET_ADMIN:*",
						"ROLE_ID_ENV:*",
						"ROLE_ID_PIVOT_ROLE:*"
					]
				}
			}
		},
```

The idea here is that dataset admin role, environment role and the pivot role have access to the bucket. However all those roles already have access to the bucket and the only way they would not have access if the bucket policy had statements restricting access to other roles which most people won't do as it's not necessary because it is enough to control permissions on the role within same account. Even if someone restricted their bucket policy to all other roles on the account then data.all would have no way to add this statement itself as no permissions would allow that. Importing such buckets would simply fail.

We have tested this and data.all functions completely fine with this block removed. Additionally the logic managing this statement has bugs. For example if you reimport a dataset then the dataset role admin id will not be updated on the bucket but everything will still continue working. The same happens if you unimport, delete an environment and reimport the bucket on a new environment the environment role id will not be updated.

Same idea is used for access points but there I'm not sure if this block is required or not. This should be checked.

I propose that we fix this by releasing a version which will clean up this block for everyone if they have it during dataset update cycle. And then during some version remove the cleanup logic as well.

**Comment by noah-paige** [comment]
I performed some quick testing on the above by removing `AllowAllToAdmin` Sid for both a created and an imported dataset and tested (for each):
- [x] Existing Bucket Share and Folder Share Still Works
- [x] Dataset Role still can upload Data


Good catch @zsaltys - the `AllowAllToAdmin` block of code may not be needed. 

Also while in OS code we add `"Sid": "AllowAllToAdmin"` ( if it does not already exist on the bucket policy) we never update/delete it once added. This makes us more prone to errors especially during deletes / clean up of resources.

I am inclined that we pick this up in an upcoming release to remove this statement from the OS code

**Comment by dlpzx** [comment]
Merged!
